{
  "hash": "491cfe1d12b2afe30833403edd1d5414",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 -  Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n## Topics\n\n-   Use simple linear regression to describe the relationship between a quantitative predictor and quantitative response variable.\n-   Estimate the slope and intercept of the regression line using R.\n\n# Data\n\n## DC Bikeshare\n\nOur data set contains daily rentals from the Capital Bikeshare in Washington, DC in 2011 and 2012. It was obtained from the `dcbikeshare` data set in the `dsbox` R package.\n\nWe will focus on the following variables in the analysis:\n\n-   `count`: total bike rentals\n-   `temp_orig`: Temperature in degrees Celsius\n-   `season`: 1 - winter, 2 - spring, 3 - summer, 4 - fall\n\nClick [here](https://tidyverse.github.io/dsbox/reference/dcbikeshare.html) for the full list of variables and definitions.\n\n## Last time {.smaller}\n\n::::{.columns}\n:::{.column}\n- Coloring and faceting our plots\n- Used `mutate` to recode `season` as a `factor` with `winter`, `fall`, `summer`, `spring`\n- Talked about how to use `filter` to select certain observations\n- Noticed that the relationship between `count` and `temp_orig` didn't really look linear:\n    - About to use `filter` for each group to select a season\n:::\n:::{.column}\n\n::: {.cell}\n::: {.cell-output-display}\n![](04-slr-intro_files/figure-revealjs/unnamed-chunk-2-1.png){width=80%}\n:::\n:::\n\n:::\n::::\n\n# Filtering our data\n\n## Filtering {.smaller}\n\n::::{.columns}\n:::{.column}\n| ID | Thing1 | Thing2 | Thing3\n--- | ------ | ------ | ------\n1   | 100   | 200   | \"Bleg\"\n2   | 20     | 20    | \"Bleg\"\n3   | 30     | 40    | \"Fleg\"\n4   | 120    | 120   | \"Fleg\"\n:::\n:::{.column}\n- To keep some observations use `filter(`\\[insert true/false statement here\\]`)` and filter will keep all rows where the inside is true.\nExamples:\n    - `Thing2 <= 100`: keeps all rows where `Thing2` is less than or equal to 1000\n    - `Thing3 == \"Fleg\"`: keeps everything where `Thing3` equals `\"Fleg\"`? (Always write strings in quotes)\n    - `Thing1 != Thing2`: keeps everything where `Thing1` isn't equal to `Thing2`?\n:::\n::::\n\n## Activity time: Picking up where we left off\n\n::: appex\n📋 [AE 03 - DC Bikeshare](../ae/ae-03-bikeshare.qmd)\n:::\n\n- Get in same groups as last time\n- Rotate rolls if you feel comfortable with someone else typing on your computer (Coder -> Communicator -> Developer -> Coder)\n- Let's divide up the seasons\n- I'm doing fall\n- Do Exercises 7 & 8\n    - Note: Exercise 7 is a challenge that is unrelated to choosing a season\n\n## Sample Solution For 8\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfall <- bikeshare |>\n  filter(season == \"fall\")\n```\n:::\n\n\n\n## Rentals vs Temperature\n\n**Goal**: Fit a line to describe the relationship between the temperature and the number of rentals in your season.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-slr-intro_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n# Simple linear regression (SLR)\n\n## SLR: Statistical model\n\n- **Simple linear regression:** model to describe the relationship between $Y$ and $X$ where:\n  + $Y$ is a quantitative/numerical response\n  + $X$ is a *single* quantitative predictor\n  + $$\\Large{Y = \\mathbf{\\beta_0 + \\beta_1 X} + \\epsilon}$$\n\n. . .\n\n-   $\\beta_1$: True slope of the relationship between $X$ and $Y$\n-   $\\beta_0$: True intercept of the relationship between $X$ and $Y$\n-   $\\epsilon$: Error\n\n## SLR: Regression equation\n\n$$\\Large{\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X}$$\n\n-   $\\hat{\\beta}_1$: Estimated slope of the relationship between $X$ and $Y$\n-   $\\hat{\\beta}_0$: Estimated intercept of the relationship between $X$ and $Y$\n-   $\\hat{Y}$: Predicted value of $Y$ for a given $X$\n-   No error term!\n\n## Statistical model vs. regression equation {.midi}\n\n**Statistical model (also known as data-generating model)**\n\n$${\\small \\text{count} = \\beta_0 + \\beta_1 ~\\text{temp_orig} + \\epsilon}$$\n\nModels the process for generating values of the response in the population (function + error)\n\n<br>\n\n. . .\n\n**Regression equation**\n\nEstimate of the function using the sample data\n\n$${\\small \\hat{\\text{count}} = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~\\text{temp_orig}}$$\n\n## Why fit a model?\n\n-   **Prediction:** Expected value of the response variable for given values of the predictor variables\n\n-   **Inference:** Conclusion about the relationship between the response and predictor variables\n\n::: question\n-   What is an example of a **prediction** question that can be answered using the model of count vs. temperature?\n\n-   What is an example of an **inference** question that can be answered using the model of count vs. temperature?\n:::\n\n\n## Choosing values for $\\hat{\\beta}_1$ and $\\hat{\\beta}_0$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-slr-intro_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n# Estimating the regression line in R\n\n## Fit model & estimate parameters\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ temp_orig, data = fall)\n\nCoefficients:\n(Intercept)    temp_orig  \n     2077.5        152.9  \n```\n\n\n:::\n:::\n\n\n## Look at the regression output\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ temp_orig, data = fall)\n\nCoefficients:\n(Intercept)    temp_orig  \n     2077.5        152.9  \n```\n\n\n:::\n:::\n\n\n\n$$\\widehat{\\text{count}} = 2077.5 + 152.9 \\times \\text{temp_orig}$$\n\n## Use `tidy` to make it prettier\n\nWe'll focus on the first column for now...\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nfall_fit |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic      p.value\n  <chr>          <dbl>     <dbl>     <dbl>        <dbl>\n1 (Intercept)    2077.     476.       4.37 0.0000214   \n2 temp_orig       153.      26.6      5.75 0.0000000387\n```\n\n\n:::\n:::\n\n\n## Using `kable` to make it extra pretty\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3\"}\nfall_fit |>\n  tidy() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|  p.value|\n|:-----------|---------:|---------:|---------:|--------:|\n|(Intercept) | 2077.4771| 475.67243|  4.367453| 2.14e-05|\n|temp_orig   |  152.8729|  26.58745|  5.749815| 0.00e+00|\n\n\n:::\n:::\n\n\n## Visualize Model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfall |>\n  gf_point(count ~ temp_orig) |>\n  gf_lm() |>\n  gf_labs(x = \"Temperature (°C)\", y = \"Daily Bike Rentals\", title = \"Fall Bike Rentals vs. Temperature\")\n```\n\n::: {.cell-output-display}\n![](04-slr-intro_files/figure-revealjs/unnamed-chunk-10-1.png){width=80%}\n:::\n:::\n\n\n# Interpretation\n\n## Interpreting the Slope and Intercept\n\n-  Slope: For each additional unit of $X$ we expect $Y$ to increase by $\\hat{\\beta}_1$, on average.\n-  Intercept: If $X$ were 0, we predict $Y$ to be $\\hat{\\beta}_0$\n\n## Fall Example\n\n- Slope: For each addition degree Celcius we expect the number of bike rentals to increase by 152.87 on average, in the Fall.\n- Intercept: If the temperature were 0 degrees Celcius, we predict the number of bike rentals to be 2077.48 in the Fall.\n\n\n## Does it make sense to interpret the intercept?\n\n✅ **The intercept is meaningful in the context of the data if**\n\n-   the predictor can feasibly take values equal to or near zero, or\n\n-   there are values near zero in the observed data.\n\n. . .\n\n🛑 Otherwise, the intercept may not be meaningful!\n\n-   Note meaningful doesn't mean wrong\n\n. . .\n\nComplete the remainder of the exercises.\n\n# Prediction\n\n## Fall Model\n\n```{=tex}\n\\begin{aligned}\n\\widehat{Y} &=  2077.48 + 152.87 \\times X\\\\\n\n\\widehat{\\text{count}} &=  2077.48 + 152.87 \\times \\text{temp_orig}\n\\end{aligned}\n```\n\n. . .\n\nOn the white board: Suppose that it's 15 degrees Celsius outside. According to this model, how many bike rentals should we expect if it's your season?\n\n## Making a prediction\n\nOn the white board: Suppose that it's 15 degrees Celsius outside. According to this model, how many bike rentals should we expect if it's your season?\n\n```{=tex}\n\\begin{aligned}\n\n\\widehat{\\text{count}} &=  2077.48 + 152.87 \\times \\text{temp_orig}\\\\\n&= 2077.48 + 152.87 \\times 15 \\\\\n&= 4370.53\n\\end{aligned}\n```\n\nAbout 4,371 rentals!\n\n## Prediction in R\n\n- `predict` function takes two arguments\n    - First: a model that's been fit\n    - Second: a new dataset with the **same column names** as the dataset used to train the model\n\n## Examples\n\n::::{.columns}\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nfall_predictions <- predict(fall_fit, fall)\nfall_predictions |>\n  head() |> # what does this do?\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|        x|\n|--------:|\n| 5895.607|\n| 5879.938|\n| 6052.302|\n| 6146.319|\n| 6067.972|\n| 6057.523|\n\n\n:::\n:::\n\n:::\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a data frame for a new temperature\nnew_days <- tibble(temp_orig = c(15, 20, 5, 10))\n\n# I don't need to save the predictions\npredict(fall_fit, new_days) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|        x|\n|--------:|\n| 4370.571|\n| 5134.935|\n| 2841.842|\n| 3606.206|\n\n\n:::\n:::\n\n:::\n::::\n\n## Exercise 14\n\n1. Add a new exercise to your activity (you can start by copy pasting a previous exercise and answer block).\n2. Confirm you answer to the white board question using the `predict` in R. I.e. what would you model predict the number of bike rentals to be if it was 15 degrees out.\n\n## Recap\n\n::: {.incremental style=\"font-size: 0.85em\"}\n- Simple linear regression (SLR) describes the relationship between a quantitative predictor ($X$) and response ($Y$).\n- The statistical model: $Y = \\beta_0 + \\beta_1 X$\n- The regression equation: $\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X$\n- $\\hat{\\beta}_1$ (slope): estimated change in $Y$ for each unit increase in $X$\n- $\\hat{\\beta}_0$ (intercept): estimated value of $Y$ when $X = 0$\n- SLR can be used for prediction and inference\n:::\n",
    "supporting": [
      "04-slr-intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}