{
  "hash": "448b0e1450bd91012e71637c20550b94",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 -  Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n## Reminder: Group Work Roles {.smaller}\n\nAny time we are working on AEs, I will randomly assign you to groups of two or three. Each person will have a role:\n\n- **Coder:**\n    +   Shares screen and is the only person to type.\n    +   Runs code, saves work, and makes the submission.\n    +   Reads comments back when asked and asks for clarification when unsure.\n- **Developer:**\n    +   Directs the next steps: explains intent, outlines logic, and points out likely errors.\n    +   Watches output, reads error messages aloud, and suggests targeted fixes.\n- **Communicator:**\n    +   Looks up help when needed.\n    +   Reports group answers to the class.\n\n# Data\n\n## DC Bikeshare\n\nOur data set contains daily rentals from the Capital Bikeshare in Washington, DC in 2011 and 2012. It was obtained from the `dcbikeshare` data set in the `dsbox` R package.\n\nWe will focus on the following variables in the analysis:\n\n-   `count`: total bike rentals\n-   `temp_orig`: Temperature in degrees Celsius\n-   `season`: 1 - winter, 2 - spring, 3 - summer, 4 - fall\n\nClick [here](https://tidyverse.github.io/dsbox/reference/dcbikeshare.html) for the full list of variables and definitions.\n\n\n## Loading Data From A File {.smaller}\n\n- PATH: directions to get to a file\n    - Example: \"ae/ae-03/dataset.csv\" will take it you to `ae` then `ae-03` then `dataset.csv`\n- Two types of paths: absolute and relative\n    - Absolute: starts from the root directory (i.e. the top-level directory)\n    - Relative: starts from the current directory (`..` goes up one level)\n- RStudio & Quarto: use `read_csv(\"relative_path/to/file.csv\")` to load data from a CSV file\n    - Brief aside: one of the few things we put in quotes in R. Use quotes when:\n        - You want R to look outside of R for something\n        - You are defining a string (i.e. a \"word\" in R)\n\n## Application exercise\n\n::: appex\n📋 [AE 03 - DC Bikeshare](../ae/ae-03-bikeshare.qmd)\n:::\n\nComplete Exercises 1-3.\n\n# Introduction to Simple Linear Regression\n\n## Function between response and predictors\n\n::: goal\n$$\\text{count} = f(\\text{temp_orig}) + \\epsilon$$\n:::\n\n-   **Goal**: Determine $f$\n-   How do we determine $f$?\n    -   Make an assumption about the functional form $f$ (parametric model)\n    -   Use the data to fit a model based on that form\n\n## Determine $f$\n\n1.  Choose the functional form of $f$, i.e., **choose the appropriate model given the response variable**\n\n-   Suppose $f$ takes the form of a linear model\\\n    $$y = f(\\mathbf{X}) = \\beta_0 + \\beta_1 x_1 + \\epsilon$$\n\n. . .\n\n2.  Use the data to fit (or train) the model, i.e, **estimate the model parameters,** $\\beta_0, \\beta_1$\n\n## Topics\n\n-   Some basic data cleaning techniques\n-   Use simple linear regression to describe the relationship between a quantitative predictor and quantitative response variable.\n-   Estimate the slope and intercept of the regression line using R.\n\n## Computational set up {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)       # for data wrangling\nlibrary(ggformula)       # for plotting\nlibrary(broom)           # for formatting model output\nlibrary(knitr)           # for formatting tables\n```\n:::\n\n\n\n\n\n## Count vs. Temperature\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-3-1.png){width=80%}\n:::\n:::\n\n\n# Adding a third variable to our plots\n\n## Skipping ahead to Exercise 5\n\n- Suppose we want to add a third variable to our plots, such as the `season` variable. We have a few options:\n    + Color the points based on the third variables (add `color = ~season` to the `gf_point` call)\n    + Facet the plots by on the third variable by changing the formula to `count ~ temp_orig | season`\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(count ~ temp_orig | season, data = bikeshare) |>\n  gf_labs(x = \"Temperature (Celsius)\",\n          y = \"Daily bike rentals\")\n```\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-4-1.png){width=80%}\n:::\n:::\n\n\n- What do we notice about how `season` is displayed\n\n\n# Data cleaning\n\n## `dplyr` and the `tidyverse`\n\n- As R is an open-source programming language there are several difference styles and ways of doing things\n- In this class we're going to use something called the `tidyverse`\n- The `tidyverse` is a collection of R packages that share a common design philosophy\n- `dplyr` is a package within the `tidyverse` that provides a consistent interface for data manipulation\n\n## `dplyr` verbs\n\n- `dplyr` provides a set of \"verbs\" for data manipulation\n- We'll going to cover two today:\n    - `mutate`: creates new columns and changes (mutates) existing columns\n    - `filter`: selects rows based on a condition\n- We'll typically chain together these verbs using the pipe operator `|>` (you may see `%>%` in older code)\n- Let's use these verbs to clean up the `bikeshare` data\n\n## Data prep {.smaller}\n\n-   R calls categorical data \"factors\"\n    - You may also see `<chr>` which stands for character. These are also categorical variables, but it's almost always better to convert them to factors\n-   Factors have levels (categories) and can be ordered or unordered\n    - You can put them in an order that makes sense so your plots looks better\n-   Exercise 4: Recode `season` as a factor with names instead of numbers (livecode)\n\n## Exercise 4 {.smaller}\n\n-   Idea:\n    +   Take the `bikeshare` data... AND THEN\n    +   Use `case_when` to mutate the `season` column... AND THEN\n    +   Use `factor` to convert `season` to a factor with levels in an order that makes sense\n\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbikeshare <- bikeshare |>\n  mutate(season = case_when(\n    season == 1 ~ \"winter\",\n    season == 2 ~ \"spring\",\n    season == 3 ~ \"summer\",\n    season == 4 ~ \"fall\"\n  ),\n  season = factor(season, levels = c(\"winter\", \"spring\", \"summer\", \"fall\")))\n```\n:::\n\n\n## Back to Exercise 5 & 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(count ~ temp_orig | season, data = bikeshare) |>\n  gf_labs(x = \"Temperature (Celsius)\",\n          y = \"Daily bike rentals\")\n```\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-6-1.png){width=80%}\n:::\n:::\n\n\n- Does it look like the relationship between `temp_orig` and `count` is the same in each season?\n- Which is strongest/weakest?\n\n## `season` is an important predictor\n\n- Later in the course we'll learn how to include both `temp_orig` and `season` in our model\n- For now, let's just focus on fitting a model to data from one season\n\n# Filtering our data\n\n## Filtering\n\n- To keep some observations use `filter(true/false statement)` and filter will keep all rows where the inside is true.\nExamples:\n    - `Thing1 > 0`: keeps all days where the temperature was above 0 degrees Celsius\n    - `Thing2 <= 1000`: keeps all days where the number of bike rentals was less than or equal to 1000\n    - `Thing1 == Thing2`: keeps everything where `Thing1` equals `Thing2`?\n    - `Thing1 != Thing2`: keeps everything where `Thing1` isn't equal to `Thing2`?\n- Each group: Choose a season.\n- Do Exercises 7 & 8\n\n\n## I'm doing fall\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfall <- bikeshare |>\n  filter(season == \"fall\")\n```\n:::\n\n\n\n## Rentals vs Temperature\n\n**Goal**: Fit a line to describe the relationship between the temperature and the number of rentals in your season.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n# Simple linear regression (SLR)\n\n## SLR: Statistical model\n\n- **Simple linear regression:** model to describe the relationship between $Y$ and $X$ where:\n  + $Y$ is a quantitative/numerical response\n  + $X$ is a *single* quantitative predictor\n  + $$\\Large{Y = \\mathbf{\\beta_0 + \\beta_1 X} + \\epsilon}$$\n\n. . .\n\n-   $\\beta_1$: True slope of the relationship between $X$ and $Y$\n-   $\\beta_0$: True intercept of the relationship between $X$ and $Y$\n-   $\\epsilon$: Error\n\n## SLR: Regression equation\n\n$$\\Large{\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X}$$\n\n-   $\\hat{\\beta}_1$: Estimated slope of the relationship between $X$ and $Y$\n-   $\\hat{\\beta}_0$: Estimated intercept of the relationship between $X$ and $Y$\n-   $\\hat{Y}$: Predicted value of $Y$ for a given $X$\n-   No error term!\n\n## Statistical model vs. regression equation {.midi}\n\n**Statistical model (also known as data-generating model)**\n\n$${\\small \\text{count} = \\beta_0 + \\beta_1 ~\\text{temp_orig} + \\epsilon}$$\n\nModels the process for generating values of the response in the population (function + error)\n\n<br>\n\n. . .\n\n**Regression equation**\n\nEstimate of the function using the sample data\n\n$${\\small \\hat{\\text{count}} = \\hat{\\beta}_0 + \\hat{\\beta}_1 ~\\text{temp_orig}}$$\n\n## Why fit a model?\n\n-   **Prediction:** Expected value of the response variable for given values of the predictor variables\n\n-   **Inference:** Conclusion about the relationship between the response and predictor variables\n\n::: question\n-   What is an example of a **prediction** question that can be answered using the model of count vs. temperature?\n\n-   What is an example of an **inference** question that can be answered using the model of count vs. temperature?\n:::\n\n\n## Choosing values for $\\hat{\\beta}_1$ and $\\hat{\\beta}_0$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n# Estimating the regression line in R\n\n## Fit model & estimate parameters\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ temp_orig, data = fall)\n\nCoefficients:\n(Intercept)    temp_orig  \n     2077.5        152.9  \n```\n\n\n:::\n:::\n\n\n## Look at the regression output\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ temp_orig, data = fall)\n\nCoefficients:\n(Intercept)    temp_orig  \n     2077.5        152.9  \n```\n\n\n:::\n:::\n\n\n\n$$\\widehat{\\text{count}} = 2077.5 + 152.9 \\times \\text{temp_orig}$$\n\n## Use `tidy` to make it prettier\n\nWe'll focus on the first column for now...\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nfall_fit |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic      p.value\n  <chr>          <dbl>     <dbl>     <dbl>        <dbl>\n1 (Intercept)    2077.     476.       4.37 0.0000214   \n2 temp_orig       153.      26.6      5.75 0.0000000387\n```\n\n\n:::\n:::\n\n\n## Using `kable` to make it extra pretty\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3\"}\nfall_fit |>\n  tidy() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|  p.value|\n|:-----------|---------:|---------:|---------:|--------:|\n|(Intercept) | 2077.4771| 475.67243|  4.367453| 2.14e-05|\n|temp_orig   |  152.8729|  26.58745|  5.749815| 0.00e+00|\n\n\n:::\n:::\n\n\n## Visualize Model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfall |>\n  gf_point(count ~ temp_orig) |>\n  gf_lm() |>\n  gf_labs(x = \"Temperature (°C)\", y = \"Daily Bike Rentals\", title = \"Fall Bike Rentals vs. Temperature\")\n```\n\n::: {.cell-output-display}\n![](03-slr-intro_files/figure-revealjs/unnamed-chunk-14-1.png){width=80%}\n:::\n:::\n\n\n# Interpretation\n\n## Interpreting the Slope and Intercept\n\n-  Slope: For each additional unit of $X$ we expect $Y$ to increase by $\\hat{\\beta}_1$, on average.\n-  Intercept: If $X$ were 0, we predict $Y$ to be $\\hat{\\beta}_0$\n\n## Fall Example\n\n- Slope: For each addition degree Celcius we expect the number of bike rentals to increase by 152.87 on average, in the Fall.\n- Intercept: If the temperature were 0 degrees Celcius, we predict the number of bike rentals to be 2077.48 in the Fall.\n\nComplete the remainder of the exercises.\n\n## Does it make sense to interpret the intercept?\n\n✅ **The intercept is meaningful in the context of the data if**\n\n-   the predictor can feasibly take values equal to or near zero, or\n\n-   there are values near zero in the observed data.\n\n. . .\n\n🛑 Otherwise, the intercept may not be meaningful!\n\n-   Note meaningful doesn't mean wrong\n\n\n## Recap\n\n::: {.incremental style=\"font-size: 0.85em\"}\n\n- Simple linear regression (SLR) describes the relationship between a quantitative predictor ($X$) and response ($Y$).\n- The regression equation: $\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X$\n- $\\hat{\\beta}_1$ (slope): estimated change in $Y$ for each unit increase in $X$\n- $\\hat{\\beta}_0$ (intercept): estimated value of $Y$ when $X = 0$\n- SLR can be used for prediction and inference\n:::\n",
    "supporting": [
      "03-slr-intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}