{
  "hash": "f17b952ac0225207c29a715cd7e96a1e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Statistical Inference\"\nsubtitle: \"Study design, sampling, and the Islands\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 - Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Topics\n\n- Distinguish a **population** from a **sample**, and a **parameter** from a **statistic**.\n- Distinguish **observational studies** from **experiments**, and connect study design to what we can conclude.\n- Describe common **sampling schemes** and how a sample can go wrong.\n- Use a regression model to answer a real question: *What is the life expectancy on the Island?*\n\n## Last time {.smaller}\n\n::: {.incremental style=\"font-size: 0.9em\"}\n- A **residual** is the gap between an observed value and the model's prediction: $e_i = y_i - \\hat{y}_i$.\n- **Least squares** picks $\\hat{\\beta}_0, \\hat{\\beta}_1$ to minimize the sum of squared residuals.\n- $R^2$ and RMSE tell us how well a model fits *the data we have*.\n:::\n\n. . .\n\n::: question\nEverything so far describes the data in front of us. What if we want to say something about data we *haven't* seen?\n:::\n\n# From sample to population\n\n## The Coffee Truck, again {.smaller}\n\nIn AE 05 and AE 06 you fit models like\n\n$$\n\\widehat{\\text{Sales}} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\times \\text{Price}\n$$\n\n::: question\n- What does $\\hat{\\beta}_1$ describe: the 60 shifts *you* simulated, or every shift Jo could ever run?\n- Would a classmate who played the same game get exactly the same $\\hat{\\beta}_1$?\n:::\n\n## Population and sample {.smaller}\n\n-   **Population:** the complete set of observations we care about (size $N$): people, shifts, cities, islanders, etc.\n-   **Sample:** the subset we actually observe (size $n$)\n-   A **parameter** is a number describing the population: $\\mu$, $\\beta_1$\n-   A **statistic** is a number computed from the sample: $\\bar{x}$, $\\hat{\\beta}_1$\n\n. . .\n\n| | Population | Sample |\n|:--|:-:|:-:|\n| Size | $N$ | $n$ |\n| Mean | $\\mu$ | $\\bar{x}$ |\n| Slope | $\\beta_1$ | $\\hat{\\beta}_1$ |\n\n. . .\n\nWe (almost) never get to see the parameter. We see a statistic and have to reason about the parameter.\n\n## Sampling is natural {.midi}\n\n![](images/03/soup.png){fig-alt=\"Illustration of a bowl of soup\" fig-align=\"center\" width=\"35%\"}\n\n- When you taste a spoonful of soup and decide it isn't salty enough, that's exploratory analysis.\n- If you conclude that the *entire pot* needs salt, that's an **inference**.\n- For your inference to be valid, the spoonful (the sample) needs to be representative of the pot (the population).\n\n## Statistical inference\n\n**Statistical inference** refers to ideas, methods, and tools for generalizing from the single sample we observed to statements about the population it came from.\n\n. . .\n\nTwo things can go wrong:\n\n::: incremental\n1. **A bad sample.** If the sample doesn't represent the population, we are biased, and no amount of math can fix that. *This is today.*\n2. **Sampling variability.** Even a perfectly good sample gives a slightly different answer each time. We can quantify this. *This is the next few weeks.*\n:::\n\n# Where do data come from?\n\n## Two kinds of studies {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Observational study**\n\n- Researchers *observe* and record what happens\n- They do **not** decide who gets which value of the explanatory variable\n:::\n\n::: {.column width=\"50%\"}\n**Experiment**\n\n- Researchers *assign* values of the explanatory variable\n- Ideally using **random assignment**\n:::\n:::\n\n. . .\n\n::: question\n- The Coffee Truck: observational or experimental? Who chose `Price`, `Music`, and `Location`?\n- The DC Bikeshare data: observational or experimental?\n:::\n\n## Observational studies come in flavors {.smaller}\n\n- **Cross-sectional:** a snapshot, everyone measured at (about) one point in time.\n- **Cohort:** follow a group of people forward in time and see what happens to them.\n- **Case-control:** start from the outcome (cases) and compare them to people without it (controls), looking backward.\n\n. . .\n\nYou'll need these words in the methods section of your Islands project.\n\n## Confounding {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-inference-islands_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n::: question\nSummer has more rentals than winter. Is it the *season* that causes riders to show up, or something that comes with the season?\n:::\n\n## Confounding {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-inference-islands_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n- A **confounding variable** is related to *both* the explanatory and the response variable, so it can create (or hide) an apparent relationship.\n- Temperature travels with season *and* drives ridership.\n\n## What can we conclude? {.smaller}\n\n|  | **Random assignment** | **No random assignment** |\n|:--|:--|:--|\n| **Random sample** | Causal conclusions **and** generalizes to the population | Association only, but generalizes to the population |\n| **No random sample** | Causal conclusions, but only for the people/units in the study | Association only, only for the people/units in the study |\n\n. . .\n\n::: question\nWhere do these studies go in the table?\n\n- The Coffee Truck\n- DC Bikeshare\n- A survey of 300 randomly chosen islanders\n:::\n\n## Sampling: how did the data get into our hands? {.smaller}\n\n-   **Simple random sample:** every member of the population is equally likely to be chosen.\n-   **Stratified sample:** split the population into groups (**strata**) that are similar inside, then randomly sample from *every* stratum.\n-   **Cluster sample:** split the population into groups (**clusters**) that each look like a mini-population, randomly choose *some* clusters, and sample within those.\n-   **Stratified cluster / multistage:** combine the two.\n-   **Convenience sample:** whoever is easiest to reach. Watch out.\n\n## Strata vs. clusters {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Stratified**\n\n- Groups are *different from each other*\n- Sample from **every** group\n- Goal: make sure every kind of unit is represented\n:::\n\n::: {.column width=\"50%\"}\n**Cluster**\n\n- Groups are *similar to each other*\n- Sample from **some** groups\n- Goal: save time and money\n:::\n:::\n\n. . .\n\n::: question\nWhich one would you use to survey College of Idaho students about their housing? By class year, or by residence hall? Which is which?\n:::\n\n## How a sample goes wrong {.smaller}\n\n-   **Convenience bias:** you sample the units that are easy to get.\n-   **Undercoverage:** part of the population isn't in your **sampling frame** (the list you sample from) at all.\n-   **Non-response:** the people you chose don't respond, and they differ from the ones who do.\n-   **Survivorship / selection bias:** the way units *enter* the data is related to the outcome.\n\n. . .\n\n::: question\nBias is a property of the *sampling process*, not the sample size. Would 1 million biased observations be better than 100 good ones?\n:::\n\n# Welcome to the Islands\n\n## The Islands {.smaller}\n\nA simulated world of thousands of **islanders**, organized into villages across several islands.\n\n- You can look up islanders, interview them, and measure things about them.\n- You can **assign** islanders to treatments, which means you can run **experiments** as well as observational studies.\n- Each islander can only do **one task at a time**, and the Islands have their own clock.\n- It's a simulation, so, in principle, we could census the whole population and check whether our inference was right.\n\n::: appex\n🏝️ [The Islands](https://islands.smp.uq.edu.au/index.php): sign in with your College of Idaho email\n:::\n\n## Finding your way around {.smaller}\n\n- **Visitor Center:** information about the islands and islanders. Start with the **Guides** tab.\n- **Academy:** example studies. Good for asking, \"what questions can be asked here?\"\n- Videos: [Island Overview](https://youtu.be/iJPgXuq6yFg), [Working with the Islanders](https://youtu.be/J00KIC0y-E8), [Finding Groups on the Islands](https://youtu.be/NFSWwxKiFZs), [Time on the Islands](https://youtu.be/R9T0PS8hV6w)\n- Trouble signing in? Use \"Need to set or reset your password?\" with your College of Idaho email.\n\n## The semester project {.smaller}\n\nYou will design, run, and analyze your own study on the Islands with a group.\n\n| Deliverable | Due |\n|:--|:--|\n| 1. Pilot | Wed, Nov 4 |\n| 2. Power | Wed, Nov 11 |\n| 3. Preliminary analysis | Wed, Nov 18 |\n| 4. Full draft | Mon, Nov 30 |\n| 5. Final report + poster | Finals week (Dec 7-10) |\n\nToday's activity is a small preview of the whole workflow: sample a population, tidy the data, fit a model, and ask what it means.\n\n# What is the life expectancy on the Island?\n\n## A real question {.smaller}\n\n::: question\n**What is the life expectancy on the Island?** Is it different for men and women?\n:::\n\n::: incremental\n- Who is the **population**?\n- Can we measure everyone?\n- What would a good **sample** look like?\n:::\n\n## How a previous class answered it {.smaller}\n\n> Using a stratified cluster sample survey, we collected data from the Island's records to calculate overall life expectancy on the Island, as well as male versus female life expectancies. We divided the island into geographic quadrants and each of us randomly collected data from birth records and individuals' information pages, sampling 3-4 cities in our respective quadrants. Masha sampled data from Fairhaven, Serrano, Sunrise and Eden. Tyler collected data from Riverside, Valkov and Rosica. Abby sampled the populations living in Edwardton, Asderaki and Mossgiel. Jess collected data in Macondo, Durand Bay and Deep Bay. The information we collected included each individual's birth year, death year and sex.\n\n## How a previous class answered it (continued) {.smaller}\n\n> Once we compiled the data for approximately 500 people, we selected the people who died between 1980 and 2010 as well as those who are alive today. We made the assumption that this selection would give us a representative picture of present or contemporary life expectancy, since living conditions throughout the last thirty years could be considered relatively consistent and relevant. We also capped the age at 150, since our oldest person in the sample was 147. Once we applied these exclusions, our data for the actual calculations included approximately 300 people - still a significant number for this type of simulation.\n\n*(They then built age-specific mortality rates from a life table. We'll come back to that.)*\n\n## Read it like a statistician {.smaller}\n\n::: question\n- What is the **population**? What is the **sampling frame**?\n- Which part is **stratified**? Which part is **clustered**?\n- Why did they keep only people who died between 1980 and 2010 (or are still alive)? What does that *assumption* buy them?\n- Why cap age at 150?\n- ~500 people sampled, ~300 analyzed. Who did we lose, and does it matter?\n:::\n\n## Life expectancy is trickier than it sounds {.smaller}\n\n**Life expectancy** is the average number of years a *newborn* today could expect to live, *if* current death rates stayed the same.\n\n. . .\n\nThe previous class computed it properly with age-specific mortality rates (a **life table**), which is what demographers do. It's a lot of tabulating.\n\n. . .\n\nToday, we'll use a simpler stand-in: **the mean age at death among islanders who have died**.\n\n::: question\n- What's the danger in averaging age at death among only the people who have died recently?\n- Who is *missing* from that group?\n:::\n\n::: {.fragment}\nSomeone born last year can't appear in it. Neither can anyone who hasn't died yet. Keep this in mind, since we'll come back to it.\n:::\n\n## Today's plan {.smaller}\n\nYou will mimic the stratified cluster design:\n\n1. Each group gets a set of villages (a **cluster**).\n2. Within those villages, sample islanders who have died, and record `sex`, `birth_year`, and `death_year` in **one shared Google Sheet**.\n3. Compute `age_at_death = death_year - birth_year`.\n4. Pool everyone's data, estimate life expectancy, and **fit a model predicting age at death from sex**.\n\n## Village assignments {.smaller}\n\n| Group | Villages |\n|:--|:--|\n| A | Fairhaven, Serrano, Sunrise, Eden |\n| B | Riverside, Valkov, Rosica |\n| C | Edwardton, Asderaki, Mossgiel |\n| D | Macondo, Durand Bay, Deep Bay |\n\n::: incremental\n- Record `sex` as exactly `Female` or `Male`.\n- Include only islanders who died in 1980 or later, and drop anything with an age over 150.\n- Enter one row per islander. **One task at a time per islander!**\n:::\n\n## Activity {.smaller}\n\n::: appex\n📋 [AE 07 - Life Expectancy on the Islands](../ae/ae-07-islands-life-expectancy.qmd)\n:::\n\nComplete Exercises 1-3 (get oriented, collect, and load your pooled data).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_b1290b8f\" minutes=\"25\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Modeling life expectancy from sex\n\n## Our pooled data {.smaller}\n\n::: callout-note\nThe output on these slides is from a **made-up** island so the slides render before you've collected anything. Yours will look different.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nislands |>\n  head(5) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|sex    | age_at_death|\n|:------|------------:|\n|Male   |           75|\n|Female |           67|\n|Female |           52|\n|Male   |           36|\n|Female |           99|\n\n\n:::\n:::\n\n\n::: question\nWhat are the observational units? What are the variables, and which is the response?\n:::\n\n## Exploring age at death {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_boxplot(age_at_death ~ sex, data = islands, fill = ~ sex, show.legend = FALSE) |>\n  gf_labs(x = \"Sex\", y = \"Age at death (years)\")\n```\n\n::: {.cell-output-display}\n![](07-inference-islands_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Fitting the model {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nle_fit <- lm(age_at_death ~ sex, data = islands)\n\ntidy(le_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    70.4       1.44     48.8  3.55e-129\n2 sexMale        -2.65      2.05     -1.29 1.97e-  1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n$$\n\\widehat{\\text{age at death}} = 70.4 - 2.65 \\times \\text{sexMale}\n$$\n\n::: question\n- What is the reference level? How can you tell?\n- What does the intercept mean? What does the slope mean?\n:::\n\n## Interpreting the model {.smaller}\n\n- **Intercept:** the mean age at death for the reference group (`Female`): 70.4 years.\n- **Slope:** the *difference in means*. Men in our sample die 2.65 years earlier, on average, than women.\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nislands |>\n  group_by(sex) |>\n  summarize(mean_age = mean(age_at_death))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sex    mean_age\n  <chr>     <dbl>\n1 Female     70.4\n2 Male       67.8\n```\n\n\n:::\n:::\n\n\nThis is the same categorical-predictor model from Lesson 5.\n\n## Work time {.smaller}\n\n::: appex\n📋 [AE 07 - Life Expectancy on the Islands](../ae/ae-07-islands-life-expectancy.qmd)\n:::\n\nComplete Exercises 4-7 (explore, fit, interpret, and critique).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_65c0ad2a\" minutes=\"15\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Is the difference between men and women real?\n\n## The question {.smaller}\n\nOur model says men and women differ by about 2.65 years in our sample.\n\n::: question\n**Is the difference between men and women real?**\n:::\n\n. . .\n\n*What could \"real\" mean here?*\n\n## Same population, different samples {.smaller}\n\nIn our made-up world we *know* the population, so let's take four more samples of the same size.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(101)\n\nmap_dfr(1:4, \\(i) {\n  island_pop |>\n    slice_sample(n = 250) |>\n    lm(age_at_death ~ sex, data = _) |>\n    tidy() |>\n    filter(term == \"sexMale\") |>\n    mutate(sample = i)\n}) |>\n  select(sample, estimate) |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| sample| estimate|\n|------:|--------:|\n|      1|    -1.68|\n|      2|    -4.28|\n|      3|    -4.20|\n|      4|    -2.14|\n\n\n:::\n:::\n\n\n::: question\nSame island, same model, same sample size. Four different slopes. Which one is \"right\"?\n:::\n\n## Two competing explanations {.smaller}\n\nIf a sample slope $\\hat{\\beta}_1$ is not zero, there are (at least) two reasons why:\n\n::: incremental\n1. There **is** a real difference in the population: $\\beta_1 \\neq 0$.\n2. There is no real difference, and we just got a **lucky (or unlucky) draw**: $\\beta_1 = 0$ but $\\hat{\\beta}_1 \\neq 0$.\n:::\n\n. . .\n\nSampling variability means a sample statistic won't equal the population parameter, so **the data alone can't tell us which explanation is right.** We need a way to measure how much a slope is *expected* to bounce around.\n\n. . .\n\n::: question\nLook at the four slopes on the previous slide. How big would the slope have to be before *you'd* be convinced?\n:::\n\n## Back to the AE {.smaller}\n\n::: appex\n📋 [AE 07 - Life Expectancy on the Islands](../ae/ae-07-islands-life-expectancy.qmd)\n:::\n\nComplete Exercises 8-9: refit the model using only your own group's villages, compare slopes on the board, and decide how confident you are.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_a9c1de4f\" minutes=\"10\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## Recap {.smaller}\n\n-   **Population** vs. **sample**, **parameter** vs. **statistic**: inference means using $\\hat{\\beta}_1$ to learn about $\\beta_1$.\n-   **Observational studies** observe; **experiments** assign. Only random assignment supports causal claims, and only random sampling supports generalizing.\n-   **Confounders** are related to both the explanatory and response variables.\n-   **Stratified** samples take units from every group; **cluster** samples take *all or some units from some groups*. Bias comes from the *sampling process*, not the sample size.\n-   A regression with a categorical predictor estimates a **difference in means**, but a different sample gives a different $\\hat{\\beta}_1$.\n-   **Next time:** how do we measure how much a slope should bounce around by chance?\n",
    "supporting": [
      "07-inference-islands_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}