{
  "hash": "d65a1a7d7070124f7ba437f093b66d6d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Residuals, Least Squares, and Model Evaluation\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 - Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Topics\n\n- Define residuals, and connect them to the idea of variation in $Y$.\n- Understand how the least squares method chooses a regression line.\n- Partition variation into model and error (ANOVA), and use it to compute $R^2$ and RMSE.\n\n## Last time {.smaller}\n\n::: {.incremental style=\"font-size: 0.9em\"}\n- Regression works with a categorical predictor $X$, just like a quantitative one.\n- R recodes a $K$-level categorical variable into $K - 1$ **indicator (dummy) variables**, dropping the **reference level**.\n- The intercept is the mean of the response at the reference level; each slope is the difference in means from that level.\n- We started playing with the **Coffee Truck** to generate our own data.\n:::\n\n# Back to the Coffee Truck\n\n## Warm-Up\n\n::: appex\n📋 [AE 06-07 - Comparing Models with the Coffee Truck](../ae/ae-06-07-coffee-truck-eval.qmd)\n:::\n\nComplete Exercise 1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_08f73ba4\" minutes=\"20\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Thinking about evaluating predictions\n\n## Quick Data Cleaning\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall <- bikeshare |>\n  filter(season == \"fall\")\n```\n:::\n\n\n::: question\n- What is this code doing?\n:::\n\n## A Simple Model For `count`\n\n:::{.incremental}\n- Let's start by considering a very basic model to predict `count`.\n- We'll write it out using a **word equation**:\n    - count = constant + error\n- Our statistical model would be:\n    - count = $\\beta_0 + \\epsilon$\n- Our regression equation would be:\n    - $\\hat{y} = \\hat{\\beta}_0$\n- What number should we use for $\\hat{\\beta}_0$?\n:::\n\n\n\n\n## How should we choose $\\hat{\\beta}_0$?\n\n- Suppose I choose $\\hat{\\beta}_0 = 4000$\n- Then I predict the number of bike rentals on a given day to be 4000\n- On a given day the actual count was 4500. What's my \"error\" for that day?\n\n## Evaluating Predictions {.smaller}\n\n::::{.columns}\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall |>\n  select(dteday, season, count) |>\n  head(3) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | count|\n|:----------|:------|-----:|\n|2011-09-23 |fall   |  2395|\n|2011-09-24 |fall   |  5423|\n|2011-09-25 |fall   |  5010|\n\n\n:::\n:::\n\n:::\n:::{.column}\n- Suppose I wanted to predict `count` (the number of bike rentals) in the fall season. Which of the following numbers is best for the first number?\n    - 3909\n    - 4276\n    - 5010\n    - 5423\n:::\n::::\n\n# Residuals\n\n## Residuals {.smaller}\n\nSuppose we have:\n\n- Prediction: $\\hat{y}_i$\n- Actual: $y_i$\n- Residual: $e_i = y_i - \\hat{y}_i$\n\n**Residual:** How much did we miss by?\n\n::: question\n- Why the subscript $i$?\n- Can residuals be negative?\n- Do we want big or small residuals?\n:::\n\n## Activity {.smaller}\n\nOn the board, compute the residuals for all three points for each prediction (you should have 6 numbers when you're done).\n\nTry and use the residuals to argue which of the two prediction is better.\n\n::::{.columns}\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall |>\n  select(dteday, season, count) |>\n  head(3) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | count|\n|:----------|:------|-----:|\n|2011-09-23 |fall   |  2395|\n|2011-09-24 |fall   |  5423|\n|2011-09-25 |fall   |  5010|\n\n\n:::\n:::\n\n:::\n:::{.column}\nPotential values of $\\hat{\\beta}_0$:\n\n- 4276 ($\\hat{y}_i = 4276$)\n- 5010 ($\\hat{y}_i = 5010$)\n:::\n::::\n\n. . .\n\nNote: 4276 is actually the mean of 2395, 5423, 5010\n\n## Interesting properties of the mean {.smaller}\n\n:::{.incremental}\n- Sum of the residuals is 0\n    - Intuitively: balances the errors on either side of the mean\n    - Would a negative or positive sum be better?\n- 4276 is the mean of 2395, 5423, 5010... Is this better than the median of 5010?\n:::\n\n## From Mean to Variability and SSE {.smaller}\n\n:::{.incremental}\n- But what is the *best* number we can use?\n- Can't sum them because some are negative...\n- What if we square each of the residuals to make them positive and then sum them?\n    - We'll call this the **Sum of Squared Error (SSE)**\n    - The mean gives use the smallest SSE possible for any single number\n- Why not just use the median?...\n    - Historically: can be done with calculus\n    - Luckily: has nice theoretical properties that go far beyond the scope of this class\n- Also... mean is the center... the SSE gives us a measure of how spread out our observations are... it gives us an idea of the amount of **variation** or **variability** in our data\n- Remember: the goals of statistics is to explain variability\n:::\n\n\n## The regression model {.smaller}\n\n- The nice thing about regression is that we don't have to predict the same value for every point.\n- Our goal should be to explain *MORE* variation than the mean.\n- We call predictions for observations that we have **fitted values**.\n\n\n\n## Residuals: Visually {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-slr-fitting_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n$$\\text{residual} = \\text{observed} - \\text{predicted} = y_i - \\hat{y}_i = e_i$$\n\n::: {.fragment}\n- A **positive** residual: the point is *above* the line (model underpredicted).\n- A **negative** residual: the point is *below* the line (model overpredicted).\n:::\n\n## Does our model explain more variation than the mean? {.smaller}\n\n::::{.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit |>\n  tidy() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|  p.value|\n|:-----------|---------:|---------:|---------:|--------:|\n|(Intercept) | 2077.4771| 475.67243|  4.367453| 2.14e-05|\n|temp_orig   |  152.8729|  26.58745|  5.749815| 0.00e+00|\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall |>\n  select(dteday, season, temp_orig, count) |>\n  head(3) |>\n  kable() \n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | temp_orig| count|\n|:----------|:------|---------:|-----:|\n|2011-09-23 |fall   |  24.97585|  2395|\n|2011-09-24 |fall   |  24.87335|  5423|\n|2011-09-25 |fall   |  26.00085|  5010|\n\n\n:::\n:::\n\n:::\n::::\n\n::: question\nOn the board:\n\n1. Compute the *fitted* values for the three points above using the model above.\n2. Compute the residuals for each of the fitted points.\n3. Compute the SSE for these three points.\n4. Are we explaining more or less variation than just using the mean as our model?\n:::\n\n# Fitting Our Model\n\n## Choosing values for $\\hat{\\beta}_1$ and $\\hat{\\beta}_0$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-slr-fitting_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n::: question\nWhich of these three lines does the \"best\" job? How would you decide?\n:::\n\n## Least squares regression {.smaller}\n\n::: incremental\n- We need a rule for picking *the* line, not just *a* line.\n- **Least squares method**: choose $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ to minimize the sum of squared error\n$$\n\\sum_{i=1}^n e_i^2 = \\sum_{i=1}^n (y_i - \\hat{y}_i)^2 = \\sum_{i=1}^n (y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_i))^2\n$$\n- If we use $\\bar{y}$ for our model this shoud look a little familiar\n$$\nSST = \\sum_{i=1}^n (y_i - \\bar{y})^2\n$$\n  - This is the numerator in the calculation of variance/standard deviation\n  - We can this of this as the Total Variation in our response variable\n- Basic idea: choose the line that explains the *most* variation in the data\n- How does one actually do this?.... Calculus (beyond the scope of this course)\n:::\n\n. . .\n\n::: small\n[Click here](https://introregression.netlify.app/appendix-linear) for details on deriving the equations for slope and intercept, which is easy if you know multivariate calculus.\n:::\n\n## Let's think about variation {.smaller}\n\n:::{.incremental}\n- DATA = MODEL + ERROR\n- $\\substack{\\text{Total Variation} \\\\ \\text{in Y}} = \\substack{\\text{Variation explained} \\\\ \\text{by model}} + \\substack{\\text{Variation not explained} \\\\ \\text{by model}}$\n- $SST = SSM + SSE$ (Note, you may see other acronym like $SSR$ instead of $SSE$)\n- $SST$ = Sum of Squares Total (same as SSE if we use the mean as our model)\n- $SSE$ = Sum of Squares Error (the amount of variation not explained by the model)\n- $SSM$ = Sum of Squares Model (the amount of variation explained by the model)\n    - We've calculated both the $SST$ and $SSE$... we can get the SSM using subtraction: $SST = SSM + SSE$\n- Every point's residual is a leftover piece of variation the model didn't explain.\n:::\n\n## Putting it all together\n\n::::{.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(fall_fit) |>\n  select(count, .fitted, .resid) |> \n  head(3) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| count|  .fitted|     .resid|\n|-----:|--------:|----------:|\n|  2395| 5895.607| -3500.6073|\n|  5423| 5879.938|  -456.9379|\n|  5010| 6052.302| -1042.3021|\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\nCompute the SST, SSM, and SSE for using the linear regression model and compare it to the same values if using the mean as our model.\n:::\n::::\n\n\n## Recap {.smaller}\n\n-   A **residual** is the leftover gap between an observed value and the model's prediction: $e_i = y_i - \\hat{y}_i$.\n-   The **least squares method** picks $\\hat{\\beta}_0, \\hat{\\beta}_1$ to minimize $\\sum e_i^2$.\n-   Can decompose total variation (SST) into variation explained by the model (SSM) and leftover variation (SSE).\n",
    "supporting": [
      "06-slr-fitting_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}