{
  "hash": "13cf11b6a5c7ae34901b62ef2bcd288e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modeling Life Expectancy\"\nsubtitle: \"Analyzing the data we collected on the Islands\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 - Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Last time {.smaller}\n\n::: {.incremental style=\"font-size: 0.9em\"}\n- A **population** is who we care about, a **sample** is who we observe, and inference uses a statistic to learn about a parameter.\n- Random sampling lets us generalize, random assignment lets us conclude causation.\n- We took a **stratified cluster sample** of the Islands: each of us drew 10 islanders who died in Island years 375-399 from our assigned village.\n:::\n\n. . .\n\n::: question\nWe now have one pooled data set. **What is the life expectancy on the Island? Is it different for men and women?**\n:::\n\n## Topics\n\n- Load and **clean** the pooled data that the class entered by hand.\n- Estimate life expectancy and fit a model predicting age at death from sex.\n- Critique what our sample can, and cannot, tell us.\n- See **sampling variability** first-hand: same population, different samples, different slopes.\n\n# Loading and cleaning the class data\n\n## Real data are messy {.smaller}\n\nEveryone typed in their own rows, so expect some surprises.\n\n::: incremental\n- Is `sex` spelled the same way every time?\n- Are there duplicate rows, missing values, or impossible ages?\n- Does every column have the type we expect (numbers stored as numbers)?\n:::\n\n. . .\n\nWe create `age_at_death = death_year - birth_year`, and then check the values before we trust them.\n\n## Activity {.smaller}\n\n::: appex\n📋 [AE 09 - Analyzing the Islands Data](../ae/ae-09-islands-analysis.qmd)\n:::\n\nComplete Exercise 1 (load, inspect, and clean the pooled data).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_ceb30ff5\" minutes=\"15\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Modeling life expectancy from sex\n\n## Our pooled data {.smaller}\n\n::: callout-note\nThe output on these slides is from a **made-up** island so the slides render without the class data. Yours will look different.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nislands |>\n  head(5) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|sex    | age_at_death|\n|:------|------------:|\n|Male   |           75|\n|Female |           67|\n|Female |           52|\n|Male   |           36|\n|Female |           99|\n\n\n:::\n:::\n\n\n::: question\nWhat are the observational units? What are the variables, and which is the response?\n:::\n\n## Exploring age at death {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_boxplot(age_at_death ~ sex, data = islands, fill = ~ sex, show.legend = FALSE) |>\n  gf_labs(x = \"Sex\", y = \"Age at death (years)\")\n```\n\n::: {.cell-output-display}\n![](09-islands-analysis_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Fitting the model {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nle_fit <- lm(age_at_death ~ sex, data = islands)\n\ntidy(le_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    70.4       1.44     48.8  3.55e-129\n2 sexMale        -2.65      2.05     -1.29 1.97e-  1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n$$\n\\widehat{\\text{age at death}} = 70.4 - 2.65 \\times \\text{sexMale}\n$$\n\n::: question\n- What is the reference level? How can you tell?\n- What does the intercept mean? What does the slope mean?\n:::\n\n## Interpreting the model {.smaller}\n\n- **Intercept:** the mean age at death for the reference group (`Female`): 70.4 years.\n- **Slope:** the *difference in means*. Men in our sample die 2.65 years earlier, on average, than women.\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nislands |>\n  group_by(sex) |>\n  summarize(mean_age = mean(age_at_death))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sex    mean_age\n  <chr>     <dbl>\n1 Female     70.4\n2 Male       67.8\n```\n\n\n:::\n:::\n\n\nThis is the same categorical-predictor model from Lesson 5.\n\n## Work time {.smaller}\n\n::: appex\n📋 [AE 09 - Analyzing the Islands Data](../ae/ae-09-islands-analysis.qmd)\n:::\n\nComplete Exercises 2-5 (explore, fit, interpret, and critique).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_f7babb34\" minutes=\"15\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Is the difference between men and women real?\n\n## The question {.smaller}\n\nOur model says men and women differ by about 2.65 years in our sample.\n\n::: question\n**Is the difference between men and women real?**\n:::\n\n. . .\n\n*What could \"real\" mean here?*\n\n## Same population, different samples {.smaller}\n\nIn our made-up world we *know* the population, so let's take four more samples of the same size.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(101)\n\nmap_dfr(1:4, \\(i) {\n  island_pop |>\n    slice_sample(n = 250) |>\n    lm(age_at_death ~ sex, data = _) |>\n    tidy() |>\n    filter(term == \"sexMale\") |>\n    mutate(sample = i)\n}) |>\n  select(sample, estimate) |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| sample| estimate|\n|------:|--------:|\n|      1|    -1.68|\n|      2|    -4.28|\n|      3|    -4.20|\n|      4|    -2.14|\n\n\n:::\n:::\n\n\n::: question\nSame island, same model, same sample size. Four different slopes. Which one is \"right\"?\n:::\n\n## Two competing explanations {.smaller}\n\nIf a sample slope $\\hat{\\beta}_1$ is not zero, there are (at least) two reasons why:\n\n::: incremental\n1. There **is** a real difference in the population: $\\beta_1 \\neq 0$.\n2. There is no real difference, and we just got a **lucky (or unlucky) draw**: $\\beta_1 = 0$ but $\\hat{\\beta}_1 \\neq 0$.\n:::\n\n. . .\n\nSampling variability means a sample statistic won't equal the population parameter, so **the data alone can't tell us which explanation is right.** We need a way to measure how much a slope is *expected* to bounce around.\n\n. . .\n\n::: question\nLook at the four slopes on the previous slide. How big would the slope have to be before *you'd* be convinced?\n:::\n\n## Back to the AE {.smaller}\n\n::: appex\n📋 [AE 09 - Analyzing the Islands Data](../ae/ae-09-islands-analysis.qmd)\n:::\n\nComplete Exercises 6-7: refit the model using only the 10 islanders *you* sampled, compare slopes on the board, and decide how confident you are.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_eee1be52\" minutes=\"10\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## Recap {.smaller}\n\n-   Hand-entered data need **cleaning** before we can trust them: check spelling, duplicates, missing values, and impossible values.\n-   The mean age at death among islanders who have died is a stand-in for life expectancy, and it is biased because of *who can appear* in the data.\n-   A regression with a categorical predictor estimates a **difference in means**, but a different sample gives a different $\\hat{\\beta}_1$.\n-   **Next time:** how do we measure how much a slope should bounce around by chance?\n",
    "supporting": [
      "09-islands-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}