{
  "hash": "038914439d990837addacffa37ee5f9c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Inference\"\nsubtitle: \"Does sex explain more variation than chance?\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 - Schedule](https://ericfriedlander.github.io/math2025-fa26/)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Last time {.smaller}\n\n::: {.incremental style=\"font-size: 0.9em\"}\n- We **collected** our stratified cluster sample of the Islands: each of us drew 10 islanders from an assigned village.\n- We thought about **who is (and isn't) in our sample**, and why that biases our estimate of life expectancy.\n:::\n\n. . .\n\n::: question\nToday: **explore** the pooled class data, then ask: is the difference we see between men and women real, or could it just be chance?\n:::\n\n## Topics\n\n- Load the pooled class data\n- **Explore** life expectancy overall and by sex.\n- Ask whether sex explains **more** variation than we'd expect by chance, and answer it by **shuffling**.\n- Build a **null distribution** and compute a **p-value**.\n- Name what shuffling can, and cannot, tell us.\n\n# Exploring life expectancy\n\n## Our pooled data {.smaller}\n\n::: callout-note\nThe output on these slides is from a **made-up** island so the slides render without the class data. Yours will look different.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nislands |>\n  head(5) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|sex    | age_at_death|\n|:------|------------:|\n|Male   |           75|\n|Female |           67|\n|Female |           52|\n|Male   |           36|\n|Female |           99|\n\n\n:::\n:::\n\n\n::: question\nWhat are the observational units? What are the variables, and which is the response?\n:::\n\n## Exploring age at death {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_boxplot(age_at_death ~ sex, data = islands, fill = ~ sex, show.legend = FALSE) |>\n  gf_labs(x = \"Sex\", y = \"Age at death (years)\")\n```\n\n::: {.cell-output-display}\n![](10-islands-inference_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Activity {.smaller}\n\n::: appex\n📋 [AE 10 - Does Sex Explain More Variation Than Chance?](../ae/ae-10-islands-inference.qmd)\n:::\n\nComplete Exercises 1-3 (load the data, explore `age_at_death`, and think critically about the sample).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_6a5a15dc\" minutes=\"10\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## Our model {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nle_fit <- lm(age_at_death ~ sex, data = islands)\n\ntidy(le_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    70.4       1.44     48.8  3.55e-129\n2 sexMale        -2.65      2.05     -1.29 1.97e-  1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n$$\n\\widehat{\\text{age at death}} = 70.4 - 2.65 \\times \\text{sexMale}\n$$\n\n::: question\nWhat is the reference level? What does the slope mean here?\n:::\n\n::: callout-note\nYou'll fit and interpret this model (and a couple more) in detail in **HW 05**.\n:::\n\n# Does sex explain *more* variation than chance?\n\n## How much does sex explain? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npre_obs <- pre(age_at_death ~ sex, data = islands)\npre_obs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006689164\n```\n\n\n:::\n:::\n\n\nIn Lesson 7 we called this **PRE** (or $R^2$): the proportion of variation in age at death that the model explains.\n\n::: question\nIn our sample, sex explains 0.7% of the variation in age at death. **Is that a lot?** What would you compare it to?\n:::\n\n## A useful model or a useless one? {.smaller}\n\nRemember, $SST = SSM + SSE$, and $PRE = SSM / SST$.\n\n::: question\nSuppose we add a predictor to the model, and the predictor is *pure noise*. Could $SSE$ get **bigger** than it was for the empty model? What is the smallest $PRE$ can ever be?\n:::\n\n. . .\n\n- Least squares can always fall back on \"ignore the predictor,\" so $SSE$ can't go up and **$PRE \\geq 0$**.\n- In practice, even a useless predictor picks up a little bit of the noise, so $PRE$ is (almost) always **a little bigger than 0**.\n\n. . .\n\n::: question\nSo \"PRE is bigger than 0\" can't be our evidence. **How big is big enough?**\n:::\n\n## Reframing the question {.smaller}\n\n::: question\nDoes sex explain **MORE** variation in age at death than we'd expect *if there were no relationship at all*?\n:::\n\n. . .\n\nTo answer this, we need to know what PRE looks like in a world where there is **no relationship** between sex and age at death.\n\n. . .\n\n::: question\n- In that world, what would the boxplots for men and women look like?\n- If I told you an islander's sex, would it help you guess their age at death?\n- Then what does it matter *which* age at death goes with *which* sex label?\n:::\n\n## Activity: Shuffling villagers {.smaller}\n\n::: appex\n🃏 **Cards!** Each of you gets one villager\n:::\n\nYour card has two halves: **sex** | **age at death**.\n\n::: incremental\n1. Sit on the **Female** or **Male** side of the room, based on the *sex* half of your card.\n2. **Round 0:** Enter your card (sex, age at death) into the shared spreadsheet.\n3. I collect every *age at death* half, **shuffle** them, and deal them back out.\n4. **Round 1:** Everyone stays put and enters what they are now holding.\n5. Repeat for a few more rounds.\n:::\n\n::: notes\nLogistics: print one card per student, drawn from the cleaned pooled data, with sex on the left half and age at death on the right half. Students keep the sex half and hand in the age half after each round. Shared spreadsheet columns: `round` (0 = original pairing), `sex`, `age_at_death`. Analyze in `scripts/10-shuffle-demo.R`.\n:::\n\n## Before we shuffle {.smaller}\n\n::: question\nMake a prediction, and talk to your neighbor:\n\n- After I shuffle, will the **average age at death** of the women in the room change? What about the men?\n- Will the *difference* between the two group averages get bigger, get smaller, or stay the same?\n- Will PRE be **exactly 0**?\n:::\n\n## What did the shuffle do? {.smaller}\n\n*(We look at the class's data in R.)*\n\n::: question\n- What did shuffling **keep the same**? (Think: the set of ages, the group sizes, SST.)\n- What did shuffling **break**?\n- Which round(s) came from a world where sex has *nothing* to do with age at death?\n- Even though we *made* sex irrelevant, PRE is not exactly 0. Why not?\n:::\n\n. . .\n\n::: question\nIf I shuffled again, would I get the same PRE? How would you describe the *pattern* across many shuffles?\n:::\n\n## Shuffling in R {.smaller}\n\n`shuffle()` does what I did with the cards: it randomly reorders `age_at_death`, leaving `sex` alone.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(9)\npre(shuffle(age_at_death) ~ sex, data = islands)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.001667765\n```\n\n\n:::\n\n```{.r .cell-code}\npre(shuffle(age_at_death) ~ sex, data = islands)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01134442\n```\n\n\n:::\n\n```{.r .cell-code}\npre(shuffle(age_at_death) ~ sex, data = islands)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.181836e-05\n```\n\n\n:::\n:::\n\n\n::: question\nSame data, same code, three different answers. Where did the randomness come from?\n:::\n\n## Real vs. shuffled {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(9)\nislands |>\n  mutate(Real = age_at_death, Shuffled = shuffle(age_at_death)) |>\n  pivot_longer(c(Real, Shuffled), names_to = \"version\", values_to = \"age\") |>\n  gf_boxplot(age ~ sex, fill = ~ sex, show.legend = FALSE) |>\n  gf_facet_wrap(~ version) |>\n  gf_labs(x = \"Sex\", y = \"Age at death (years)\")\n```\n\n::: {.cell-output-display}\n![](10-islands-inference_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: question\nWhich panel looks like a world with no relationship? Which one do we actually live in?\n:::\n\n## Shuffling 1000 times {.smaller}\n\n::: question\n**Before I run this:** if I shuffle and compute PRE 1000 times, and make a histogram, what shape will it have? Where will most of the values be? Can any be negative?\n:::\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2025)\nnull_pre <- do(1000) * pre(shuffle(age_at_death) ~ sex, data = islands)\n\nhead(null_pre, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           pre\n1 2.179792e-02\n2 4.395283e-05\n3 3.044563e-03\n```\n\n\n:::\n:::\n\n\n## The null distribution {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_histogram(~ pre, data = null_pre, bins = 30, boundary = 0, fill = \"grey70\", color = \"white\") |>\n  gf_labs(x = \"PRE from a shuffled data set\", y = \"Number of shuffles\")\n```\n\n::: {.cell-output-display}\n![](10-islands-inference_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: question\nEach bar is built from shuffles where sex and age at death are **unrelated**. What does one value in this histogram represent?\n:::\n\n## Naming what we built {.smaller}\n\nThis histogram is the **sampling distribution of PRE under the null hypothesis**, or the **null distribution**.\n\n. . .\n\n-   **Null hypothesis** $H_0$: there is **no relationship** between sex and age at death ($\\beta_1 = 0$). Any PRE we see is just chance.\n-   **Alternative hypothesis** $H_A$: there **is** a relationship ($\\beta_1 \\neq 0$).\n\n. . .\n\nThe shuffles show us how much variation sex would \"explain\" *by chance alone*. That is what we needed to judge whether 0.7% is a lot.\n\n## Where does our data land? {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_histogram(~ pre, data = null_pre, bins = 30, boundary = 0, fill = \"grey70\", color = \"white\") |>\n  gf_vline(xintercept = pre_obs, color = \"#d53a19\", linewidth = 1.5) |>\n  gf_labs(x = \"PRE from a shuffled data set\", y = \"Number of shuffles\")\n```\n\n::: {.cell-output-display}\n![](10-islands-inference_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: question\nThe red line is the PRE from our *real* data. Is it an unusual value in a world with no relationship? How would you put a number on \"unusual\"?\n:::\n\n## The p-value {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_val <- mean(null_pre$pre >= pre_obs)\np_val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2\n```\n\n\n:::\n:::\n\n\nAbout 20% of the shuffled data sets explained **at least as much** variation as our real data did.\n\n. . .\n\nThis is the **p-value**: the probability of getting a PRE at least as large as ours *if there were no relationship*.\n\n::: question\n- Why do we count only the shuffles that are *bigger* than ours, and not the ones that are smaller?\n- If the p-value were tiny, what would we conclude? If it were large?\n:::\n\n## What would change the answer? {.smaller}\n\n::: question\n- Our card deck had about 20 villagers. Our pooled data have 250. Would the null distribution be wider or narrower with only 20? What would that do to how convincing a given PRE is?\n- If sex mattered *a lot* on the Island, where would the red line sit?\n- Suppose the p-value is tiny. Does that fix the survivorship bias we discussed earlier?\n:::\n\n. . .\n\nShuffling accounts for **chance**. It does *not* account for **bias** in how we collected the data, and it doesn't tell us about **cause**.\n\n## Back to the AE {.smaller}\n\n::: appex\n📋 [AE 10 - Does Sex Explain More Variation Than Chance?](../ae/ae-10-islands-inference.qmd)\n:::\n\nComplete Exercises 4-6 (Part 2): shuffle the data yourself and decide whether sex explains *more* variation than chance would.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_f06a5fac\" minutes=\"10\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## Recap {.smaller}\n\n-   Hand-entered data need **cleaning** before we can trust them: check spelling, duplicates, missing values, and impossible values.\n-   PRE is never negative, so \"PRE > 0\" is not evidence. The real question is whether sex explains **more** variation than we'd expect if there were **no relationship**.\n-   **Shuffling** the response breaks any relationship, so repeated shuffles build the **null distribution**: what PRE looks like by chance alone.\n-   The **p-value** is the proportion of shuffles that did at least as well as our real data.\n-   Shuffling accounts for chance, not for bias in how we collected our sample, and it doesn't tell us about cause.\n-   **HW 05 Part 1 is now unlocked:** clean the class data and fit models to it.\n-   **Next time:** turning this idea into a formal hypothesis test.\n",
    "supporting": [
      "10-islands-inference_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}