{
  "hash": "3cc62e987534a22f4ec27388a534b6b6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 12: Exam 1 Practice\"\nsubtitle: \"Lectures 0 to 11\"\neditor: visual\nexecute:\n  message: false\n  warning: false\nformat:\n  html:\n    embed-resources: true\n    include-in-header:\n      text: |\n        <style>\n        /* Exercise / answer boxes. Canonical source: style/exercise-boxes.css\n           in the course repo: copy from there if this ever drifts. */\n        body { counter-reset: exercise; }\n        .exercise, .answer {\n          border-left: 4px solid #533860;\n          padding: .6em 1em;\n          margin: 1em 0;\n          border-radius: 4px;\n        }\n        .exercise { background: #f2eef5; }\n        .exercise::before {\n          counter-increment: exercise;\n          content: \"Exercise \" counter(exercise);\n          display: block;\n          font-weight: 700;\n          color: #533860;\n          text-transform: uppercase;\n          letter-spacing: .04em;\n          font-size: .85em;\n          margin-bottom: .35em;\n        }\n        .answer {\n          background: transparent;\n          border-left-color: #a49363;\n          border-left-style: dashed;\n          min-height: 3.5em;\n        }\n        .answer::before {\n          content: \"Your answer\";\n          display: block;\n          font-weight: 700;\n          color: #8a7a4f;\n          text-transform: uppercase;\n          letter-spacing: .04em;\n          font-size: .85em;\n          margin-bottom: .35em;\n        }\n        .quarto-dark .exercise {\n          background: rgba(255, 255, 255, .08);\n          border-left-color: #FFCB70;\n        }\n        .quarto-dark .exercise::before {\n          color: #FFCB70;\n        }\n        .quarto-dark .answer::before {\n          color: #ffd283;\n        }\n        </style>\n  pdf:\n    documentclass: article\n    fontsize: 11pt\n    geometry: \"margin=0.8in\"\n    colorlinks: true\n    filters:\n      - ../style/exercise-boxes-pdf.lua\n    include-in-header:\n      text: |\n        \\usepackage{booktabs}\n        \\usepackage{needspace}\n        \\usepackage{xcolor}\n        \\definecolor{cofipurple}{HTML}{533860}\n        \\newcounter{exn}\n        \\setlength{\\parindent}{0pt}\n        \\setlength{\\parskip}{4pt}\n---\n\n## About the Data Sets In This Exam\n\nThree real data sets appear in this exam. Only the variables listed below are used. You do not need to know anything about these data beyond what is written here and in the questions. The other questions (for example, the fertilizer table, the cyclist experiment, and the student responses) use made-up scenarios that are fully described where they appear.\n\n### `rail_trail`: daily use of a rail trail (Exercises 1, 3, 4, 11, 12, 20, 22)\n\nA rail trail is a former railway line that has been converted to a path for walking and biking. Each row is **one day**, and the data cover **90 days** in total (62 weekdays and 28 weekend days). Spring, Summer, and Fall days are all included.\n\n| Variable | Type | Meaning |\n|:----------------|:----------------|:-------------------------------------|\n| `volume` | quantitative | Number of people who used the trail that day (users per day). Ranges from 129 to 736. |\n| `hightemp` | quantitative | The day's high temperature, in degrees Fahrenheit. Ranges from 41 to 97. |\n| `cloudcover` | quantitative | A measure of cloud cover on a scale from 0 to 10. Larger values mean a cloudier day. |\n| `precip` | quantitative | Precipitation that day, in inches. Ranges from 0 to 1.49. |\n| `season` | categorical | Spring, Summer, or Fall. |\n| `day_type` | categorical | Weekday or Weekend. |\n\n### `tip`: tips at a restaurant (Exercises 13 and 16)\n\nA server at a restaurant recorded information about **169 parties** (groups of customers) who were served. Each row is **one party's bill**.\n\n| Variable | Type | Meaning |\n|:----------------|:----------------|:-------------------------------------|\n| `Tip` | quantitative | The tip left, in dollars. |\n| `Meal` | categorical | The meal the party ate: Dinner (100 parties), Late Night (37), or Lunch (32). |\n| `Alcohol` | categorical | Whether the party ordered alcohol: Yes (48 parties) or No (121). |\n| `Tip Percentage` | quantitative | The tip as a proportion of the bill before the tip (for example, 0.18 means an 18% tip). In Exercise 16 it is multiplied by 100 so that it is measured in percentage points. |\n\n### `lego`: LEGO sets (Exercise 14)\n\nEach row is **one LEGO set**. The full data set has **400 sets** that span many themes. Exercise 14 shows only 8 sets from three themes (Star Wars, Friends, and DUPLO), which are stored in a data frame called `lego_small`.\n\n| Variable | Type | Meaning |\n|:----------------|:----------------|:-------------------------------------|\n| `Set_Name` | categorical | The name of the set. |\n| `Theme` | categorical | The product line the set belongs to (for example, Star Wars, DUPLO, Friends, or NINJAGO). |\n| `Pieces` | quantitative | The number of pieces in the set. |\n| `Price` | quantitative | The price of the set, in US dollars. |\n\n\n\n::: callout-important\n- This is a **practice** exam for Exam 1 (Lectures 0 to 11). It matches the format of the real exam: four sections, a mix of multiple choice, short answer, true/false, and evaluating a response.\n- Print it and take it in **one 75-minute sitting** with only a **calculator** and **one handwritten notes sheet** (front and back). No computers, phones, or textbooks.\n- **Do not look at the [solutions](https://ericfriedlander.github.io/math2025-fa26/ae/ae-12-exam01-practice-solutions.html) until you are done.** Then grade yourself using the point values.\n:::\n\n## Instructions\n\n- You have **75 minutes**. The exam is worth **100 points**. The suggested time for each section is in the table below, so pace yourself.\n- You may use a calculator and one handwritten notes sheet. You will **not** write any code. Some questions show R code or R output for you to *read* and *interpret*.\n- **Show your work.** Partial credit is real, and a correct answer with no work may not receive full credit.\n- Write in complete sentences when a question asks you to interpret or explain, and always use the **context** of the problem (units, variable names).\n- If a number from a table or software is needed, the exam gives it to you. No tables or software are needed.\n- Rounding: unless told otherwise, round to two decimal places. Small differences from rounding are fine.\n\n| Section   | Style                         | Questions | Points  | Suggested time |\n|:--------------|:--------------|:-------------:|:-------------:|:-------------:|\n| A         | Multiple choice               |   1-10    |   20    |     12 min     |\n| B         | Short answer                  |   11-15   |   40    |     30 min     |\n| C         | True/False with justification |   16-20   |   20    |     15 min     |\n| D         | Evaluate a response           |   21-22   |   20    |     18 min     |\n| **Total** |                               |           | **100** |   **75 min**   |\n\n```{=latex}\n\\newpage\n```\n\n------------------------------------------------------------------------\n\n## Section A: Multiple Choice (20 points, 2 points each)\n\nCircle one answer for each question. No justification is needed.\n\n::: exercise\n**(2 pts)** A researcher wants to compare the number of people who use a rail trail (`volume`, per day) on weekdays and weekends (`day_type`). Which plot is the most appropriate way to display this relationship?\n\n(A) A histogram of `volume` alone\n\n(B) A bar chart of `day_type`\n\n(C) Side-by-side boxplots of `volume`, one for each `day_type`\n\n(D) A scatterplot of `volume` against `day_type`\n:::\n\n::: exercise\n**(2 pts)** Which of the following is a **statistical model** for the population (as opposed to a fitted regression equation from a sample)?\n\n(A) $\\hat{y} = 12 + 3.5x$\n\n(B) $y = \\beta_0 + \\beta_1 x + \\epsilon$\n\n(C) $\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 x$\n\n(D) $y = b_0 + b_1 x$\n:::\n\n::: exercise\n**(2 pts)** The scatterplot below shows daily trail volume against the day's high temperature for 90 days, with the least squares line. Two days are labeled, P and Q.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ae-12-exam01-practice_files/figure-html/resid-plot-1.png){fig-align='center' width=576}\n:::\n:::\n\n\nWhich statement about the residuals for P and Q is correct?\n\n(A) P has a positive residual and Q has a negative residual\n\n(B) P has a negative residual and Q has a positive residual\n\n(C) Both residuals are positive\n\n(D) Both residuals are zero, because the line passes through the middle of the data\n:::\n\n::: exercise\n**(2 pts)** A model predicts `volume` from `season`, which has three levels: Fall, Spring, and Summer. R uses Fall as the reference level (it comes first alphabetically). Which statement is true?\n\n(A) The model uses three indicator variables, one for each season\n\n(B) The intercept is the mean `volume` for Fall days\n\n(C) The intercept is the overall mean `volume` of all 90 days\n\n(D) The coefficient for Spring is the mean `volume` of Spring days\n:::\n\n::: exercise\n**(2 pts)** For a simple linear regression, $SST = 200$ and $SSE = 50$. What is $R^2$?\n\n(A) 0.25\n\n(B) 0.50\n\n(C) 0.75\n\n(D) 4.00\n:::\n\n::: exercise\n**(2 pts)** Researchers recruit 80 volunteer cyclists. They flip a coin to assign 40 to take a caffeine supplement and 40 to take a placebo, then compare their times in a time trial. Cyclists taking caffeine are faster by a statistically significant amount. Which conclusion is most appropriate?\n\n(A) Caffeine causes faster times for cyclists in general\n\n(B) Caffeine causes faster times for these volunteers, but we cannot be sure it generalizes to all cyclists\n\n(C) Caffeine is only associated with faster times, but the result generalizes to all cyclists\n\n(D) Caffeine is only associated with faster times, and only for these volunteers\n:::\n\n::: exercise\n**(2 pts)** A local radio station asks listeners to call in and vote on whether the city should build a new stadium. About 2,000 people call, and 78% are in favor. Which statement best describes the result?\n\n(A) The result is not biased, because the sample size is so large\n\n(B) The result is likely biased, because people with strong opinions are more likely to call\n\n(C) The result is a stratified random sample of the city\n\n(D) The only concern is sampling variability, which a larger sample would remove\n:::\n\n::: exercise\n**(2 pts)** A school district has 40 elementary schools with very similar student bodies. To estimate average commute time, it randomly selects 5 schools and surveys **every** student at those 5 schools. What kind of sample is this?\n\n(A) Simple random sample\n\n(B) Stratified sample\n\n(C) Cluster sample\n\n(D) Convenience sample\n:::\n\n::: exercise\n**(2 pts)** Holding everything else fixed, which change would make the standard error of a regression slope **smaller**?\n\n(A) Using a smaller sample\n\n(B) Collecting data with a wider spread of $x$ values\n\n(C) Having more scatter of the points around the line\n\n(D) Using a larger value of the slope\n:::\n\n::: exercise\n**(2 pts)** Suppose 100 groups each collect their own data set and each conduct the same hypothesis test at the 0.05 level. If the null hypothesis were true, about how many of the groups would you expect to get a p-value below 0.05?\n\n(A) 0\n\n(B) 5\n\n(C) 95\n\n(D) 100\n:::\n\n------------------------------------------------------------------------\n\n## Section B: Short Answer (40 points)\n\nShow your work. Use full sentences and context for interpretations.\n\n::: exercise\n**(14 pts)** The `rail_trail` data record the number of people using a rail trail (`volume`, users per day) on 90 days, along with the day's high temperature (`hightemp`, degrees F, ranging from 41 to 97). We fit a model predicting `volume` from `hightemp`:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  -17.079|    59.395|     -0.29|   0.774|\n|hightemp    |    5.702|     0.848|      6.72|  <0.001|\n\n\n:::\n:::\n\n\n(a) **(2 pts)** Write the fitted regression equation. Use $\\widehat{\\text{volume}}$ and `hightemp` in your equation.\n\n(b) **(2 pts)** Interpret the slope in context.\n\n(c) **(2 pts)** Interpret the intercept in context. Does the interpretation make sense here? Explain.\n\n(d) **(2 pts)** Predict the volume on a day with a high of 80 degrees. Then explain why you would not trust the model's prediction for a day with a high of 20 degrees.\n\n(e) **(2 pts)** Write the null and alternative hypotheses for a test of whether there is a linear relationship between `hightemp` and `volume`. Show how the `statistic` for `hightemp` is computed from the other columns and state the degrees of freedom\n\n(f) **(4 pts)** Imagine building the null distribution for this slope by shuffling `volume`. (i) Where is that distribution centered, and what is its standard deviation? (ii) Using the t-statistic, is our observed slope surprising under the null? Explain. (iii) State the p-value we'd use for this test. (iv) State your conclusion of the test in context. (You may use the p-value in the table.)\n:::\n\n::: {.answer style=\"min-height: 22em;\"}\n:::\n\n::: exercise\n**(7 pts)** Consider a different model for the same 90 days, predicting `volume` from `cloudcover`. The fitted slope is **negative**. Part of the ANOVA table is below. Entries marked with a \"?\" are missing.\n\n| Source |  df |        SS |\n|:-------|----:|----------:|\n| Model  |   1 |   202,863 |\n| Error  |   ? |         ? |\n| Total  |  89 | 1,445,958 |\n\n(a) **(2 pts)** Fill in the missing degrees of freedom and the missing sum of squares. How many days are in the data?\n\n(b) **(2 pts)** Compute $R^2$ and interpret it in context.\n\n(c) **(2 pts)** Compute the RMSE and interpret it in context, including units.\n\n(d) **(1 pt)** What is the correlation $r$ between `cloudcover` and `volume`? Give its sign and value.\n:::\n\n::: {.answer style=\"min-height: 14em;\"}\n:::\n\n::: exercise\n**(7 pts)** The `tip` data record the tip (in dollars) left by 169 parties at a restaurant, along with the type of `Meal`. Here is some R code and its output:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip |>\n  group_by(Meal) |>\n  summarize(n = n(), mean_tip = mean(Tip))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Meal       |   n| mean_tip|\n|:----------|---:|--------:|\n|Dinner     | 100|    5.606|\n|Late Night |  37|    2.504|\n|Lunch      |  32|    5.886|\n\n\n:::\n:::\n\n\nWe fit a regression predicting `Tip` from `Meal`. R treats `Meal` as a categorical variable, and the **reference level is `Dinner`**.\n\n(a) **(2 pts)** To fit this regression, R turns `Meal` into indicator (dummy) variables. Three parties are shown below, one from each level of `Meal`. Create the indicator variables the model uses: label each one, and write down its value for each of the three parties.\n\n| Party | `Meal`     |\n|:-----:|:-----------|\n|   1   | Dinner     |\n|   2   | Late Night |\n|   3   | Lunch      |\n\n\\vspace{3cm}\n\n(b) **(2 pts)** Based on the R output above, write down the estimated regression equation. Round to the nearest cent. *Hint: you will have to do a little bit of subtraction.*\n\n(c) **(2 pts)** Interpret the coefficient for `MealLate Night` in context.\n\n(d) **(1 pt)** Why does it make sense to fit a regression with `Meal` as the predictor, but not to compute a correlation between `Meal` and `Tip`?\n:::\n\n::: {.answer style=\"min-height: 14em;\"}\n:::\n\n::: exercise\n**(6 pts)** Below are 8 sets from the `lego` data, stored in a data frame called `lego_small`. Each row is a LEGO set, with its theme, number of pieces, and price in dollars.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Set_Name                       |Theme     | Pieces|  Price|\n|:------------------------------|:---------|------:|------:|\n|Friends Advent Calendar        |Friends   |    500|  29.99|\n|Droid Commander                |Star Wars |   1177| 199.99|\n|Fire Station                   |DUPLO     |     76|  49.99|\n|Friendship Bus                 |Friends   |    778|  69.99|\n|Han Solo's Landspeeder         |Star Wars |    345|  29.99|\n|Modular Playhouse              |DUPLO     |    129|  59.99|\n|Emma's Deluxe Bedroom          |Friends   |    183|  14.99|\n|Resistance Y-wing Microfighter |Star Wars |     86|   9.99|\n\n\n:::\n:::\n\n\nConsider these two pipelines:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pipeline 1\nlego_small |>\n  filter(Pieces > 650) |>\n  mutate(price_per_piece = Price / Pieces) |>\n  select(Set_Name, price_per_piece)\n\n# Pipeline 2\nlego_small |>\n  group_by(Theme) |>\n  summarize(mean_price = mean(Price))\n```\n:::\n\n\n(a) **(3 pts)** Write out the data frame that Pipeline 1 produces: give its column names and every row. Round `price_per_piece` to three decimal places.\n\n(b) **(3 pts)** For Pipeline 2, how many rows and how many columns does the result have, and what are the column names? What is `mean_price` for the Star Wars theme?\n:::\n\n::: {.answer style=\"min-height: 12em;\"}\n:::\n\n::: exercise\n**(6 pts)** A community garden tests two fertilizers, X and Y. Each is applied to 100 plots of land (i.e. patches of dirt), and a plot counts as a \"success\" if the plants thrive. The garden also records whether each plot is sunny or shady.\n\n|              |         Sunny plots          |         Shady plots          |\n|:-------------|:----------------------------:|:----------------------------:|\n| Fertilizer X | 72 successes out of 80 plots | 4 successes out of 20 plots  |\n| Fertilizer Y | 19 successes out of 20 plots | 28 successes out of 80 plots |\n\n(a) **(2 pts)** Compute the overall success rate for each fertilizer, ignoring sunlight. Which fertilizer looks better?\n\n(b) **(2 pts)** Compute the success rate for each fertilizer separately for sunny plots and for shady plots. Which fertilizer looks better within each type of plot?\n\n(c) **(2 pts)** Name this phenomenon. Identify the confounding variable and explain in one or two sentences why the overall comparison and the within-group comparisons disagree.\n:::\n\n::: {.answer style=\"min-height: 14em;\"}\n:::\n\n------------------------------------------------------------------------\n\n## Section C: True/False with Justification (20 points, 4 points each)\n\nFor each statement, circle **True** or **False**, and then **justify your answer** in one to three sentences. A correct justification is worth most of the points. If a statement is false, say what is wrong with it or what would make it true.\n\n::: exercise\n**(4 pts)** A restaurant manager wonders whether parties that order alcohol tip a different percentage of the bill than parties that do not. Using the `tip` data, she computes the difference in mean tip percentage (alcohol minus no alcohol) and gets $-0.99$ percentage points. She shuffles the tip percentages 1,000 times and records the difference in mean tip percentage each time. The histogram of the shuffled differences is below, with the observed difference shown as a red line.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ae-12-exam01-practice_files/figure-html/shuffle-plot-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n**Statement:** About 45% of the shuffled differences are at least as far from 0 as the red line, so the p-value is about 0.45. This is strong evidence that parties that order alcohol and parties that do not tip the same percentage, on average.\n\nTrue / False. Justify:\n:::\n\n::: {.answer style=\"min-height: 7em;\"}\n:::\n\n::: exercise\n**(4 pts)** A researcher takes a random sample of 400 adults in Idaho and records each person's weekly hours of exercise and a depression score. She finds a clear negative association. **Statement:** Because the sample was randomly selected, this study shows that more exercise **causes** lower depression scores.\n\nTrue / False. Justify:\n:::\n\n::: {.answer style=\"min-height: 7em;\"}\n:::\n\n::: exercise\n**(4 pts)** A researcher fits a simple linear regression and then collects a new data set that is twice as large (twice as many observations), with the same spread in $x$ and the same scatter around the line. **Statement:** The standard error of the slope in the larger data set will be smaller than before.\n\nTrue / False. Justify:\n:::\n\n::: {.answer style=\"min-height: 7em;\"}\n:::\n\n::: exercise\n**(4 pts)** A simple linear regression has $R^2 = 0.64$ and a negative slope. **Statement:** The correlation between the two variables is $r = 0.8$.\n\nTrue / False. Justify:\n:::\n\n::: {.answer style=\"min-height: 7em;\"}\n:::\n\n::: exercise\n**(4 pts)** Consider the rail trail data from earlier. Suppose you build two different linear models predicting `volume` from `hightemp`, one treating `hightemp` as a quantitative variable and one treating `hightemp` as a categorical variable. **Statement:** While the model treating `hightemp` as a categorical variable will likely have an $R^2$ at or near 1, it is almost certainly best to treat `hightemp` as a quantitative variable.\n\nTrue / False. Justify:\n:::\n\n::: {.answer style=\"min-height: 7em;\"}\n:::\n\n------------------------------------------------------------------------\n\n## Section D: Evaluate a Response (20 points)\n\nIn each question, a fictional student has written a response. Your job is to **grade the reasoning**, not to write your own full answer. For each numbered claim, say whether it is **correct** or **incorrect**. If it is incorrect, explain what is wrong and write a corrected statement.\n\n::: exercise\n**(10 pts)** A university wants to know whether a new peer-mentoring program improves first-year retention. It emails all first-year students and invites them to join a study. Of those who respond, 200 volunteer. The researchers flip a coin for each volunteer to decide whether the student is placed in the mentoring program (100 students) or a comparison group (100 students). After one year, 90% of the mentored students and 80% of the comparison students are still enrolled. The difference is statistically significant.\n\nHere is Jordan's response to the question \"What can we conclude?\"\n\n> (1) Since the students were randomly assigned, we can conclude that the mentoring program caused the higher retention among these volunteers.\n>\n> (2) The 200 volunteers are a big sample, so the fact that they volunteered does not matter. We can conclude the program would raise retention for all first-year students at this university.\n>\n> (3) We can also conclude that the program would raise retention for first-year students at every college in the country.\n\nEvaluate each numbered claim. (Claim 1 is worth 4 points, and claims 2 and 3 are worth 3 points each.)\n:::\n\n::: {.answer style=\"min-height: 16em;\"}\n:::\n\n::: exercise\n**(10 pts)** Using the `rail_trail` data again, a student studies whether the day's rainfall (`precip`, in inches, from 0 to 1.49) is related to trail volume (users per day). The data cover 90 days. The output for the model predicting `volume` from `precip` is below. For this model, $R^2 = 0.054$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   385.82|     13.94|     27.68|  <0.001|\n|precip      |  -112.59|     50.23|     -2.24|   0.028|\n\n\n:::\n:::\n\n\nHere is Riley's response.\n\n> (1) The p-value is 0.028, which is less than 0.05. This means there is only a 2.8% chance that the null hypothesis is true.\n>\n> (2) To build a null distribution, I shuffle the `volume` values many times and recompute the slope each time. These shuffled slopes will be centered at my observed slope of $-112.59$, because shuffling keeps the relationship in the data.\n>\n> (3) Because the slope is statistically significant, we can conclude that rainfall causes volume to decrease.\n>\n> (4) Because the slope is statistically significant, rainfall is a strong predictor that explains most of the variation in trail volume.\n\nEvaluate each numbered claim. (Claims 1 and 2 are worth 3 points each, and claims 3 and 4 are worth 2 points each.)\n:::\n\n::: {.answer style=\"min-height: 18em;\"}\n:::\n\n------------------------------------------------------------------------\n\n*End of exam. If you finish early, go back and check your units and your interpretations.*",
    "supporting": [
      "ae-12-exam01-practice_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}