{
  "hash": "3e25b9ad3c7a9914fa80a79ad207dac2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 12: Exam 1 Practice Solutions\"\nsubtitle: \"Answer key with worked solutions\"\neditor: visual\nformat:\n  html:\n    embed-resources: true\n    include-in-header:\n      text: |\n        <style>\n        /* Exercise / answer boxes. Canonical source: style/exercise-boxes.css\n           in the course repo: copy from there if this ever drifts. */\n        body { counter-reset: exercise; }\n        .exercise, .answer {\n          border-left: 4px solid #533860;\n          padding: .6em 1em;\n          margin: 1em 0;\n          border-radius: 4px;\n        }\n        .exercise { background: #f2eef5; }\n        .exercise::before {\n          counter-increment: exercise;\n          content: \"Exercise \" counter(exercise);\n          display: block;\n          font-weight: 700;\n          color: #533860;\n          text-transform: uppercase;\n          letter-spacing: .04em;\n          font-size: .85em;\n          margin-bottom: .35em;\n        }\n        .answer {\n          background: transparent;\n          border-left-color: #a49363;\n          border-left-style: dashed;\n          min-height: 3.5em;\n        }\n        .answer::before {\n          content: \"Your answer\";\n          display: block;\n          font-weight: 700;\n          color: #8a7a4f;\n          text-transform: uppercase;\n          letter-spacing: .04em;\n          font-size: .85em;\n          margin-bottom: .35em;\n        }\n        .quarto-dark .exercise {\n          background: rgba(255, 255, 255, .08);\n          border-left-color: #FFCB70;\n        }\n        .quarto-dark .exercise::before {\n          color: #FFCB70;\n        }\n        .quarto-dark .answer::before {\n          color: #ffd283;\n        }\n        /* Solutions: numbered to match the exam exercises. */\n        .keysol {\n          border-left: 4px solid #a49363;\n          background: #faf6ea;\n          padding: .6em 1em;\n          margin: 1em 0;\n          border-radius: 4px;\n        }\n        .keysol::before {\n          counter-increment: exercise;\n          content: \"Solution \" counter(exercise);\n          display: block;\n          font-weight: 700;\n          color: #6f6240;\n          text-transform: uppercase;\n          letter-spacing: .04em;\n          font-size: .85em;\n          margin-bottom: .35em;\n        }\n        .grading {\n          font-size: .92em;\n          border-top: 1px dotted #a49363;\n          margin-top: .6em;\n          padding-top: .4em;\n        }\n        .quarto-dark .keysol {\n          background: rgba(255, 255, 255, .08);\n          border-left-color: #FFCB70;\n        }\n        .quarto-dark .keysol::before {\n          color: #FFCB70;\n        }\n        </style>\n---\n\n\n\n::: callout-important\nThis is the answer key for the [AE 12 practice exam](https://ericfriedlander.github.io/math2025-fa26/ae/ae-12-exam01-practice.html). **Try the exam first**, under timed conditions, before reading this page. Solution numbers match the exercise numbers on the exam.\n:::\n\n## Answer summary\n\n| Section             | Answers                                           |\n|:--------------------|:--------------------------------------------------|\n| A (Questions 1-10)  | 1 C, 2 B, 3 A, 4 B, 5 C, 6 B, 7 B, 8 C, 9 B, 10 B |\n| B (Questions 11-15) | Worked solutions below                            |\n| C (Questions 16-20) | 16 False, 17 False, 18 True, 19 False, 20 True    |\n| D (Questions 21-22) | Worked solutions below                            |\n\n------------------------------------------------------------------------\n\n## Section A: Multiple Choice (2 points each)\n\n::: keysol\n**C.** Volume is quantitative and `day_type` is categorical, so side-by-side boxplots (or jitter plots) are the right choice. A histogram or bar chart shows only one variable, and a scatterplot needs two quantitative variables.\n:::\n\n::: keysol\n**B.** $y = \\beta_0 + \\beta_1 x + \\epsilon$ uses Greek letters (population parameters) and includes the error term $\\epsilon$. Options A and C are fitted equations (hats, no error), and D mixes the two.\n:::\n\n::: keysol\n**A.** A residual is observed minus predicted. P lies above the line, so its residual is positive (the model underpredicted). Q lies below the line, so its residual is negative (the model overpredicted). Residuals sum to 0 overall, but individual residuals are almost never 0.\n:::\n\n::: keysol\n**B.** With $K = 3$ levels there are $K - 1 = 2$ indicator variables, and the reference level (Fall) is the one with no indicator. The intercept is the mean response at the reference level, and each coefficient is a *difference* from that mean.\n:::\n\n::: keysol\n**C.** $SSM = SST - SSE = 200 - 50 = 150$, so $R^2 = 150/200 = 0.75$. (Equivalently, $1 - 50/200 = 0.75$.)\n:::\n\n::: keysol\n**B.** Random assignment supports a causal conclusion, but the cyclists are volunteers rather than a random sample of all cyclists, so we cannot generalize beyond them.\n:::\n\n::: keysol\n**B.** This is a voluntary response sample. People with strong opinions self-select, so the sample is likely not representative. A large sample does not fix bias.\n:::\n\n::: keysol\n**C.** The schools are the clusters. Whole groups that look alike were randomly selected, and everyone in the chosen groups was surveyed. A stratified sample would take some students from **every** school.\n:::\n\n::: keysol\n**B.** PRE can never be negative, because adding a predictor can only reduce (or keep) the SSE. So even a predictor with no real relationship to the response will usually give PRE above 0 just by chance. To judge whether $PRE = 0.02$ is more than chance, we shuffle the response many times, build a null distribution of PREs, and see where 0.02 lands. Option D makes the opposite mistake: a small PRE is not proof of \"no relationship\" either.\n:::\n\n::: keysol\n**B.** If the null hypothesis is true, a p-value is below 0.05 with probability 0.05, so we expect about $100 \\times 0.05 = 5$ of the 100 groups to get a p-value below 0.05. These are false positives: they happen by chance alone, even though there is no real effect. Option C (95) is the number we would expect to get a p-value *above* 0.05. Options A and D are the common misconception that either all or none of the tests will agree.\n:::\n\n------------------------------------------------------------------------\n\n## Section B: Short Answer (40 points)\n\n:::: keysol\nOutput from the exam:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  -17.079|    59.395|     -0.29|   0.774|\n|hightemp    |    5.702|     0.848|      6.72|  <0.001|\n\n\n:::\n:::\n\n\n(a) $\\widehat{\\text{volume}} = -17.08 + 5.70 \\times \\text{hightemp}$. (Using 5.702 is also fine.)\n\n(b) For each additional degree F in the day's high temperature, the predicted trail volume increases by about 5.70 users per day, on average.\n\n(c) On a day with a high temperature of 0 degrees F, the model predicts about $-17.08$ users. This does not make sense: a negative number of users is impossible, and 0 degrees is far outside the range of the data (41 to 97 degrees), so the intercept is an extrapolation and is not meaningful on its own. It simply anchors the line.\n\n(d) $\\widehat{\\text{volume}} = -17.08 + 5.70(80) = 438.9$, so about **439 users**. A high of 20 degrees is outside the range of the data (41 to 97), so predicting there is **extrapolation**: we have no evidence the linear pattern continues, and the line would predict $-17.08 + 5.70(20) \\approx 97$, which may be wrong.\n\n(e) $H_0: \\beta_1 = 0$ (there is no linear relationship between high temperature and trail volume). $H_A: \\beta_1 \\neq 0$ (there is a linear relationship).\n\n(f) (i) Shuffling `volume` randomly re-pairs each day's volume with a high temperature, which **breaks** any real relationship. The shuffled PREs show what PRE looks like by chance alone: they are never negative and pile up near 0 (small values). (ii) Yes, it is very surprising. Our observed PRE is about 0.34, and none of the 1,000 shuffles reached it, so chance alone almost never explains this much variation. (iii) The p-value is about 0 (fewer than 1 in 1,000, so we would report it as less than 0.001). (iv) There is very strong evidence of a relationship between a day's high temperature and the trail volume: temperature explains much more of the variation in volume than we would expect by chance. (Since the slope is positive, warmer days are associated with more trail users.)\n\n::::\n\n:::: keysol\n(a) $SSE = SST - SSM = 1{,}445{,}958 - 202{,}863 = 1{,}243{,}095$. The SSE measures the variation in daily trail volume that is **left over** (not explained by cloud cover): the sum of the squared residuals.\n\n(b) $R^2 = \\dfrac{SSM}{SST} = \\dfrac{202{,}863}{1{,}445{,}958} = 0.140$. About 14.0% of the variability in daily trail volume is explained by the cloud cover.\n\n(c) $RMSE = \\sqrt{SSE/n} = \\sqrt{1{,}243{,}095/90} = \\sqrt{13{,}812} \\approx 117.5$ users. The model's predictions of daily trail volume typically miss by roughly 117 users.\n\n(d) $|r| = \\sqrt{R^2} = \\sqrt{0.140} \\approx 0.375$. The slope is negative, so $r \\approx -0.37$ (or $-0.38$).\n\n::::\n\n:::: keysol\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Meal       |   n| mean_tip|\n|:----------|---:|--------:|\n|Dinner     | 100|    5.606|\n|Late Night |  37|    2.504|\n|Lunch      |  32|    5.886|\n\n\n:::\n:::\n\n\n(a) A categorical variable with $K = 3$ levels needs $K - 1 = 2$ indicator variables, one for each level except the reference level (Dinner). The two indicators are `MealLate Night` and `MealLunch`.\n\n| Party | `Meal`     | `MealLate Night` | `MealLunch` |\n|:-----:|:-----------|:----------------:|:-----------:|\n|   1   | Dinner     |        0         |      0      |\n|   2   | Late Night |        1         |      0      |\n|   3   | Lunch      |        0         |      1      |\n\n(b) The intercept is the mean tip at the reference level, 5.606, or **\\$5.61**. Each coefficient is the difference in means from the reference level. `MealLate Night`: 2.504 - 5.606 = -3.10. `MealLunch`: 5.886 - 5.606 = +0.28. So\n\n$$\\widehat{\\text{Tip}} = 5.61 - 3.10 \\times \\text{MealLate Night} + 0.28 \\times \\text{MealLunch}$$\n\n(c) Parties at late night meals tip, on average, \\$3.10 less than parties at dinner. (The predicted mean tip at late night is 5.61 - 3.10 = 2.50 dollars.)\n\n(d) A correlation measures the strength of a *linear* association between two *quantitative* variables. `Meal` is categorical, so it has no numerical order or distance. Regression works with a categorical predictor because the indicator variables turn each category into a 0/1 variable.\n\n::::\n\n:::: keysol\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Set_Name        | price_per_piece|\n|:---------------|---------------:|\n|Droid Commander |            0.17|\n|Friendship Bus  |            0.09|\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Theme     | mean_price|\n|:---------|----------:|\n|DUPLO     |      54.99|\n|Friends   |      38.32|\n|Star Wars |      79.99|\n\n\n:::\n:::\n\n\n(a) Pipeline 1 keeps only sets with more than 650 pieces, which leaves **2 rows**: Droid Commander (1177 pieces) and Friendship Bus (778 pieces). The other six sets have 500 pieces or fewer. `select()` keeps only two columns, so the data frame has **2 columns**, `Set_Name` and `price_per_piece`:\n\n| Set_Name        | price_per_piece |\n|:----------------|----------------:|\n| Droid Commander |           0.170 |\n| Friendship Bus  |           0.090 |\n\n(Droid Commander: $199.99/1177 = 0.170$. Friendship Bus: $69.99/778 = 0.090$.)\n\n(b) Pipeline 2 gives one row per theme. There are 3 themes, so the result has **3 rows and 2 columns**: `Theme` and `mean_price`. For Star Wars, $(199.99 + 29.99 + 9.99)/3 = 79.99$, so `mean_price` is about **\\$79.99**. (The other rows are DUPLO, \\$54.99, and Friends, \\$38.32.)\n\n::::\n\n:::: keysol\n(a) Fertilizer X: $(72 + 4)/100 = 76\\%$. Fertilizer Y: $(19 + 28)/100 = 47\\%$. Overall, **X** looks much better.\n\n(b) Sunny plots: X $= 72/80 = 90\\%$, Y $= 19/20 = 95\\%$. Shady plots: X $= 4/20 = 20\\%$, Y $= 28/80 = 35\\%$. Within **both** types of plot, **Y** looks better.\n\n(c) This is **Simpson's paradox**: the overall comparison reverses once we account for a third variable. The confounder is **sunlight** (sunny vs. shady plots). Sunny plots have a high success rate regardless of fertilizer, and fertilizer X was used mostly on sunny plots (80 of 100), while Y was used mostly on shady plots (80 of 100). So X's overall rate is inflated by the sunny plots it happened to get, not by the fertilizer itself.\n\n::::\n\n------------------------------------------------------------------------\n\n## Section C: True/False with Justification (4 points each)\n\n:::: keysol\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ae-12-exam01-practice-solutions_files/figure-html/shuffle-plot-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n**False.** The p-value reading is fine: the proportion of the 1,000 shuffles at least as far from 0 as the observed difference is 0.45, so the p-value is about 0.45. But a large p-value only says the data are **consistent with** no difference. We do not have convincing evidence of a difference, but that is not evidence that the groups tip the same. Absence of evidence is not evidence of absence. (The observed difference of about 1 percentage point might be a real difference that this sample is too small to detect.)\n\n::::\n\n:::: keysol\n**False.** Random **sampling** lets us generalize results to the population, but only random **assignment** (an experiment) supports a causal claim. This is an observational study, so we can only conclude an association. Other variables, such as age, health, or job, could be confounders. (It could also be that depression reduces exercise.)\n\n::::\n\n:::: keysol\n**True.** With only 20 observations, a lucky shuffle can easily produce a large PRE, so the shuffled PREs are spread out and reach much larger values. With 200 observations, shuffled PREs stay clustered close to 0. So the same observed PRE of 0.10 sits well inside the null distribution for the small study (large p-value, not convincing) but far out in the tail for the large study (small p-value, convincing). Sample size changes how much evidence a given PRE provides.\n\n::::\n\n:::: keysol\n**False.** $r^2 = R^2$, so $|r| = \\sqrt{0.64} = 0.8$. The slope has the same sign as $r$, so with a negative slope, $r = -0.8$.\n\n::::\n\n:::: keysol\n\n::: {.cell}\n\n:::\n\n\n**True.** Treating `hightemp` as categorical fits a separate mean for every distinct temperature, so the model has a huge amount of flexibility. A line is a special case of \"one free mean per temperature,\" so the categorical model's $R^2$ can never be lower than the quantitative model's, and as more and more temperatures appear only once, it gets closer and closer to 1. (In the rail trail data there are 44 distinct high temperatures among 90 days, and $R^2$ rises from 0.34 for the line to 0.68 for the categorical model.) But that higher $R^2$ is mostly the model memorizing individual days, not learning a pattern. It is still best to treat `hightemp` as quantitative because:\n\n- It gives **one slope** that we can interpret (\"each extra degree is associated with about 5.7 more users\") instead of dozens of separate coefficients.\n- It can **predict at a temperature we did not observe** (for example 62.5 degrees), while the categorical model cannot.\n- It uses **2 parameters instead of dozens**, so it explains the pattern with far less risk of fitting noise.\n\n::::\n\n------------------------------------------------------------------------\n\n## Section D: Evaluate a Response (20 points)\n\n:::: keysol\n**Claim 1 (4 points): Correct.** The students were randomly assigned to the two groups, so differences in retention can be attributed to the program, at least for the students in the study. The statement is careful to say \"among these volunteers.\"\n\n**Claim 2 (3 points): Incorrect.** The 200 students are **volunteers** who responded to an email, not a random sample of first-year students, so the result may not generalize even to all first-years at this university (for example, motivated students may be more likely to volunteer). Also, a **bigger sample does not fix bias**: bias comes from how the sample was chosen, and a large biased sample is still biased. A correct statement: \"The program caused higher retention among these volunteers. Because they are not a random sample, we cannot be confident the result applies to all first-years at this university.\"\n\n**Claim 3 (3 points): Incorrect.** The study took place at only one university, and the participants were volunteers there, so there is no basis for generalizing to every college in the country. Different colleges have different students, resources, and support systems, and none of those colleges were sampled. A correct statement: \"We can conclude the program caused higher retention among these volunteers at this university, and nothing more.\"\n\n::::\n\n:::: keysol\n**Claim 1 (3 points): Incorrect.** The p-value is the probability of seeing a slope at least this extreme **if the null hypothesis were true**. It is not the probability that the null hypothesis is true. A correct statement: \"If there were no relationship between rainfall and volume, we would see a slope this far from 0 only about 2.8% of the time. This is moderate evidence of a relationship.\"\n\n**Claim 2 (3 points): Incorrect.** Shuffling **breaks** the relationship, so the shuffled PREs show what happens when there is **no** relationship. They pile up near 0 (PRE is never negative), not at the observed PRE of 0.054. The observed PRE is then compared with that distribution: the p-value is the proportion of shuffles with a PRE at least as large as 0.054. A correct statement: \"The shuffled PREs will be small and clustered near 0, because shuffling removes any relationship. I will see what share of them are at least as large as my observed PRE.\"\n\n**Claim 3 (2 points): Incorrect.** A small p-value says the slope is unlikely to be 0 if there were no relationship, so it is evidence of an **association**. It does not show **cause**. The trail days were not randomly assigned a rainfall amount (this is an observational study), so other variables could be involved. For example, rainy days also tend to be cloudier (in these data, `precip` and `cloudcover` are positively correlated), and cloud cover alone could be what keeps people off the trail. A correct statement: \"Rainfall is associated with lower trail volume, but this observational study cannot show that rain causes the decrease.\"\n\n**Claim 4 (2 points): Incorrect.** Statistical significance is not the same as a strong relationship. Here $R^2 = 0.054$, so rainfall explains only about 5.4% of the variability in trail volume. Most of the variation is due to other factors (such as temperature). A correct statement: \"The slope is statistically significant, but rainfall explains only about 5% of the variability in volume, so on its own it is a weak predictor.\"\n\n::::\n\n------------------------------------------------------------------------\n\n## Scoring guide\n\n| Section   | Points possible | Your score |\n|:----------|:---------------:|:----------:|\n| A         |       20        |            |\n| B         |       40        |            |\n| C         |       20        |            |\n| D         |       20        |            |\n| **Total** |     **100**     |            |\n\nIf you scored below about 70, go back to the topics for the questions you missed using the [study guide](https://ericfriedlander.github.io/math2025-fa26/slides/12-exam-01-review.html), and redo related AE and HW questions.",
    "supporting": [
      "ae-12-exam01-practice-solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}