{
  "hash": "c28294bb756c5aa665308b5c0f72d519",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Residuals, Least Squares, and Model Evaluation\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2026 - Schedule](https://ericfriedlander.github.io/math2025-fa26/schedule)\"\nlogo: \"../images/logo.png\"\nformat:\n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false\n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk:\n    R.options:\n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Topics\n\n- Define residuals, and connect them to the idea of variation in $Y$.\n- Understand how the least squares method chooses a regression line.\n- Partition variation into model and error (ANOVA), and use it to compute $R^2$ and RMSE.\n\n## Last time {.smaller}\n\n::: {.incremental style=\"font-size: 0.9em\"}\n- Regression works with a categorical predictor $X$, just like a quantitative one.\n- R recodes a $K$-level categorical variable into $K - 1$ **indicator (dummy) variables**, dropping the **reference level**.\n- The intercept is the mean of the response at the reference level; each slope is the difference in means from that level.\n- We started playing with the **Coffee Truck** to generate our own data.\n:::\n\n# Back to the Coffee Truck\n\n## Warm-Up\n\n::: appex\n📋 [AE 06 - Comparing Models with the Coffee Truck](../ae/ae-06-coffee-truck-eval.qmd)\n:::\n\nComplete Exercise 1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_db511fc9\" minutes=\"20\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Thinking about evaluating predictions\n\n## Quick Data Cleaning\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall <- bikeshare |>\n  filter(season == \"fall\")\n```\n:::\n\n\n::: question\n- What is this code doing?\n:::\n\n## A Simple Model For `count`\n\n:::{.incremental}\n- Let's start by considering a very basic model to predict `count`.\n- We'll write it out using a **word equation**:\n    - count = constant + error\n- Our statistical model would be:\n    - count = $\\beta_0 + \\epsilon$\n- Our regression equation would be:\n    - $\\hat{y} = \\hat{\\beta}_0$\n- What number should we use for $\\hat{\\beta}_0$?\n:::\n\n\n\n\n## How should we choose $\\hat{\\beta}_0$?\n\n- Suppose I choose $\\hat{\\beta}_0 = 4000$\n- Then I predict the number of bike rentals on a given day to be 4000\n- On a given day the actual count was 4500. What's my \"error\" for that day?\n\n## Evaluating Predictions {.smaller}\n\n::::{.columns}\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall |>\n  select(dteday, season, count) |>\n  head(3) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | count|\n|:----------|:------|-----:|\n|2011-09-23 |fall   |  2395|\n|2011-09-24 |fall   |  5423|\n|2011-09-25 |fall   |  5010|\n\n\n:::\n:::\n\n:::\n:::{.column}\n- Suppose I wanted to predict `count` (the number of bike rentals) in the fall season. Which of the following numbers is best for the first number?\n    - 3909\n    - 4276\n    - 5010\n    - 5423\n:::\n::::\n\n# Residuals\n\n## Residuals {.smaller}\n\nSuppose we have:\n\n- Prediction: $\\hat{y}_i$\n- Actual: $y_i$\n- Residual: $e_i = y_i - \\hat{y}_i$\n\n**Residual:** How much did we miss by?\n\n::: question\n- Why the subscript $i$?\n- Can residuals be negative?\n- Do we want big or small residuals?\n:::\n\n## Activity {.smaller}\n\nOn the board, compute the residuals for all three points for each prediction (you should have 6 numbers when you're done).\n\nTry and use the residuals to argue which of the two prediction is better.\n\n::::{.columns}\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall |>\n  select(dteday, season, count) |>\n  head(3) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | count|\n|:----------|:------|-----:|\n|2011-09-23 |fall   |  2395|\n|2011-09-24 |fall   |  5423|\n|2011-09-25 |fall   |  5010|\n\n\n:::\n:::\n\n:::\n:::{.column}\nPotential values of $\\hat{\\beta}_0$:\n\n- 4276\n- 5010\n:::\n::::\n\n. . .\n\n\n## Interesting properties of the mean {.smaller}\n\n:::{.incremental}\n- Sum of the residuals is 0\n    - Intuitively: balances the errors on either side of the mean\n    - Would a negative or positive sum be better?\n- 4276 is the mean of 2395, 5423, 5010... Is this better than the median of 5010?\n:::\n\n## From Mean to Variability and SSE {.smaller}\n\n:::{.incremental}\n- But what is the *best* number we can use?\n- Can't sum them because some are negative...\n- What if we square each of the residuals to make them positive and then sum them?\n    - We'll call this the **Sum of Squared Error (SSE)**\n    - The mean gives use the smallest SSE possible for any single number\n- Why not just use the median?...\n    - Historically: can be done with calculus\n    - Luckily: has nice theoretical properties that go far beyond the scope of this class\n- Also... mean is the center... the SSE gives us a measure of how spread out our observations are... it gives us an idea of the amount of **variation** or **variability** in our data\n- Remember: the goals of statistics is to explain variability\n:::\n\n\n## The regression model {.smaller}\n\n- The nice thing about regression is that we don't have to predict the same value for every point.\n- Our goal should be to explain *MORE* variation than the mean.\n- We call predictions for observations that we have **fitted values**.\n\n\n\n## Residuals: Visually {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-slr-fitting-eval_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n$$\\text{residual} = \\text{observed} - \\text{predicted} = y_i - \\hat{y}_i = e_i$$\n\n::: {.fragment}\n- A **positive** residual: the point is *above* the line (model underpredicted).\n- A **negative** residual: the point is *below* the line (model overpredicted).\n:::\n\n## Does our model explain more variation than the mean? {.smaller}\n\n::::{.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall_fit <- lm(count ~ temp_orig, data = fall)\nfall_fit |>\n  tidy() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|  p.value|\n|:-----------|---------:|---------:|---------:|--------:|\n|(Intercept) | 2077.4771| 475.67243|  4.367453| 2.14e-05|\n|temp_orig   |  152.8729|  26.58745|  5.749815| 0.00e+00|\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#|echo: true\nfall |>\n  select(dteday, season, temp_orig, count) |>\n  head(3) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|dteday     |season | temp_orig| count|\n|:----------|:------|---------:|-----:|\n|2011-09-23 |fall   |  24.97585|  2395|\n|2011-09-24 |fall   |  24.87335|  5423|\n|2011-09-25 |fall   |  26.00085|  5010|\n\n\n:::\n:::\n\n:::\n::::\n\n::: question\nOn the board:\n\n1. Compute the *fitted* values for the three points above using the model above.\n2. Compute the residuals for each of the fitted points.\n3. Compute the SSE for these three points.\n4. Are we explaining more or less variation than just using the mean as our model?\n:::\n\n# Fitting Our Model\n\n## Choosing values for $\\hat{\\beta}_1$ and $\\hat{\\beta}_0$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-slr-fitting-eval_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n::: question\nWhich of these three lines does the \"best\" job? How would you decide?\n:::\n\n## Least squares regression {.smaller}\n\n::: incremental\n- We need a rule for picking *the* line, not just *a* line.\n- **Least squares method**: choose $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ to minimize the sum of squared error\n$$\n\\sum_{i=1}^n e_i^2 = \\sum_{i=1}^n (y_i - \\hat{y}_i)^2 = \\sum_{i=1}^n (y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_i))^2\n$$\n- If we use $\\bar{x}$ for our model this shoud look a little familiar\n$$\nSST = \\sum_{i=1}^n (y_i - \\bar{x})^2\n$$\n  - This is the numerator in the calculation of variance/standard deviation\n  - We can this of this as the Total Variation in our response variable\n- Basic idea: choose the line that explains the *most* variation in the data\n- How does one actually do this?.... Calculus (beyond the scope of this course)\n:::\n\n. . .\n\n::: small\n[Click here](https://introregression.netlify.app/98-appendix) for details on deriving the equations for slope and intercept, which is easy if you know multivariate calculus.\n:::\n\n## Let's think about variation {.smaller}\n\n:::{.incremental}\n- DATA = MODEL + ERROR\n- $\\substack{\\text{Total Variation} \\\\ \\text{in Y}} = \\substack{\\text{Variation explained} \\\\ \\text{by model}} + \\substack{\\text{Variation not explained} \\\\ \\text{by model}}$\n- $SST = SSM + SSE$ (Note, you may see other acronym like $SSR$ instead of $SSE$)\n- $SST$ = Sum of Squares Total (same as SSE if we use the mean as our model)\n- $SSE$ = Sum of Squares Error (the amount of variation not explained by the model)\n- $SSM$ = Sum of Squares Model (the amount of variation explained by the model)\n    - We've calculated both the $SST$ and $SSE$... we can get the SSM using subtraction: $SST = SSM + SSE$\n- Every point's residual is a leftover piece of variation the model didn't explain.\n:::\n\n## Putting it all together\n\n::::{.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(fall_fit) |>\n  select(count, .fitted, .resid) |> \n  head(3) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| count|  .fitted|     .resid|\n|-----:|--------:|----------:|\n|  2395| 5895.607| -3500.6073|\n|  5423| 5879.938|  -456.9379|\n|  5010| 6052.302| -1042.3021|\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\nCompute the SST, SSM, and SSE for using the linear regression model and compare it to the same values if using the mean as our model.\n:::\n::::\n\n\n## Properties of least squares regression {.smaller}\n\n::: incremental\n-   Passes through the center of mass point, the coordinates corresponding to average $X$ and average $Y$: $\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1\\bar{X}$\n-   Slope has same sign as the correlation coefficient: $\\hat{\\beta}_1 = r \\frac{s_Y}{s_X}$\n    + $r$: correlation coefficient\n    + $s_Y, s_X$: sample standard deviations of $X$ and $Y$\n-   Sum of the residuals is zero: $\\sum_{i = 1}^n e_i \\approx 0$ (sound familiar?)\n    +   Intuition: Residuals are \"balanced\"\n-   The residuals and $X$ values are uncorrelated\n:::\n\n## Partitioning Variability (ANOVA)\n\n:::{.incremental}\n-   $y_i - \\bar{y} = (\\hat{y}_i - \\bar{y}) + (y_i-\\hat{y}_i)$\n-   Square and sum: $\\sum(y_i-\\bar{y})^2 = \\sum(\\hat{y} - \\bar{y})^2 + \\sum(y-\\hat{y})^2$\n-   $\\substack{\\text{Sum of squares} \\\\ \\text{Total}} = \\substack{\\text{Sum of squares} \\\\ \\text{model}} + \\substack{\\text{Sum of squares} \\\\ \\text{error}}$\n-   $SSTotal = SSModel + SSE$\n-   $SST = SSM + SSE$\n-    This process of partitioning variability is called **Analysis of Variance (ANOVA)**: Analysis of Variance\n  -   Involves a whole different way of thinking about modeling and experiemental design\n:::\n\n## Residuals in R\n\n- `augment` function takes a model and a dataset and computes the residuals, fitted values and many other useful quantities\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(fall_fit, fall) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| instant|dteday     |season | yr| mnth| holiday| weekday| workingday| weathersit|     temp|    atemp|      hum| windspeed| casual| registered| count| temp_orig|  .fitted|      .resid|      .hat|   .sigma|   .cooksd| .std.resid|\n|-------:|:----------|:------|--:|----:|-------:|-------:|----------:|----------:|--------:|--------:|--------:|---------:|------:|----------:|-----:|---------:|--------:|-----------:|---------:|--------:|---------:|----------:|\n|     266|2011-09-23 |fall   |  0|    9|       0|       5|          1|          2| 0.609167| 0.522125| 0.972500| 0.0783667|    258|       2137|  2395| 24.975847| 5895.607| -3500.60733| 0.0224743| 1545.328| 0.0589228| -2.2640077|\n|     267|2011-09-24 |fall   |  0|    9|       0|       6|          0|          2| 0.606667| 0.564412| 0.862500| 0.0783833|   1776|       3647|  5423| 24.873347| 5879.938|  -456.93786| 0.0220248| 1567.946| 0.0009830| -0.2954553|\n|     268|2011-09-25 |fall   |  0|    9|       0|       0|          0|          2| 0.634167| 0.572637| 0.845000| 0.0503792|   1544|       3466|  5010| 26.000847| 6052.302| -1042.30206| 0.0273028| 1566.298| 0.0064092| -0.6757770|\n|     269|2011-09-26 |fall   |  0|    9|       0|       1|          1|          2| 0.649167| 0.589042| 0.848333| 0.1107000|    684|       3946|  4630| 26.615847| 6146.319| -1516.31889| 0.0304915| 1564.008| 0.0152484| -0.9847213|\n|     270|2011-09-27 |fall   |  0|    9|       0|       2|          1|          2| 0.636667| 0.574525| 0.885417| 0.1181710|    477|       3643|  4120| 26.103347| 6067.972| -1947.97153| 0.0278191| 1561.208| 0.0228340| -1.2633034|\n|     271|2011-09-28 |fall   |  0|    9|       0|       3|          1|          2| 0.635000| 0.575158| 0.848750| 0.1486290|    480|       3427|  3907| 26.035000| 6057.523| -2150.52312| 0.0274742| 1559.647| 0.0274649| -1.3944153|\n|     272|2011-09-29 |fall   |  0|    9|       0|       4|          1|          1| 0.616667| 0.574512| 0.699167| 0.1728830|    653|       4186|  4839| 25.283347| 5942.616| -1103.61575| 0.0238591| 1566.060| 0.0062349| -0.7142664|\n|     273|2011-09-30 |fall   |  0|    9|       0|       5|          1|          1| 0.564167| 0.544829| 0.647500| 0.2064750|    830|       4372|  5202| 23.130847| 5613.557|  -411.55682| 0.0153133| 1568.021| 0.0005469| -0.2652036|\n|     274|2011-10-01 |fall   |  0|   10|       0|       6|          0|          2| 0.410000| 0.412863| 0.753750| 0.2922960|    480|       1949|  2429| 16.810000| 4647.271| -2218.27059| 0.0056989| 1559.293| 0.0057990| -1.4225062|\n|     275|2011-10-02 |fall   |  0|   10|       0|       0|          0|          2| 0.356667| 0.345317| 0.791667| 0.2220130|    616|       2302|  2918| 14.623347| 4312.991| -1394.99060| 0.0077498| 1564.758| 0.0031315| -0.8954870|\n|     276|2011-10-03 |fall   |  0|   10|       0|       1|          1|          2| 0.384167| 0.392046| 0.760833| 0.0833458|    330|       3240|  3570| 15.750847| 4485.355|  -915.35480| 0.0063471| 1566.798| 0.0011012| -0.5871793|\n|     277|2011-10-04 |fall   |  0|   10|       0|       2|          1|          1| 0.484167| 0.472858| 0.710000| 0.2058540|    486|       3970|  4456| 19.850847| 5112.134|  -656.13370| 0.0074414| 1567.544| 0.0006648| -0.4211268|\n|     278|2011-10-05 |fall   |  0|   10|       0|       3|          1|          1| 0.538333| 0.527138| 0.647917| 0.1772500|    559|       4267|  4826| 22.071653| 5451.635|  -625.63476| 0.0120914| 1567.613| 0.0009914| -0.4024956|\n|     279|2011-10-06 |fall   |  0|   10|       0|       4|          1|          1| 0.494167| 0.480425| 0.620833| 0.1349540|    639|       4126|  4765| 20.260847| 5174.812|  -409.81159| 0.0080853| 1568.026| 0.0002822| -0.2631150|\n|     280|2011-10-07 |fall   |  0|   10|       0|       5|          1|          1| 0.510833| 0.504404| 0.684167| 0.0223917|    949|       4036|  4985| 20.944153| 5279.271|  -294.27056| 0.0093743| 1568.175| 0.0001691| -0.1890561|\n|     281|2011-10-08 |fall   |  0|   10|       0|       6|          0|          1| 0.521667| 0.513242| 0.701250| 0.0454042|   2235|       3174|  5409| 21.388347| 5347.176|    61.82421| 0.0103570| 1568.327| 0.0000083|  0.0397391|\n|     282|2011-10-09 |fall   |  0|   10|       0|       0|          0|          1| 0.540833| 0.523983| 0.727500| 0.0634500|   2397|       3114|  5511| 22.174153| 5467.304|    43.69577| 0.0123748| 1568.331| 0.0000050|  0.0281152|\n|     283|2011-10-10 |fall   |  0|   10|       1|       1|          0|          1| 0.570833| 0.542925| 0.733750| 0.0423042|   1514|       3603|  5117| 23.404153| 5655.338|  -538.33790| 0.0162499| 1567.798| 0.0009949| -0.3470653|\n|     284|2011-10-11 |fall   |  0|   10|       0|       2|          1|          2| 0.566667| 0.546096| 0.808750| 0.1430420|    667|       3896|  4563| 23.233347| 5629.226| -1066.22630| 0.0156595| 1566.229| 0.0037562| -0.6871876|\n|     285|2011-10-12 |fall   |  0|   10|       0|       3|          1|          3| 0.543333| 0.517717| 0.906250| 0.2481500|    217|       2199|  2416| 22.276653| 5482.974| -3066.97371| 0.0126644| 1550.881| 0.0249828| -1.9736778|\n|     286|2011-10-13 |fall   |  0|   10|       0|       4|          1|          2| 0.589167| 0.551804| 0.896667| 0.1417870|    290|       2623|  2913| 24.155847| 5770.252| -2857.25155| 0.0190487| 1553.099| 0.0330396| -1.8446898|\n|     287|2011-10-14 |fall   |  0|   10|       0|       5|          1|          2| 0.550833| 0.529675| 0.716250| 0.2238830|    529|       3115|  3644| 22.584153| 5529.982| -1885.98212| 0.0135694| 1561.752| 0.0101407| -1.2142354|\n|     288|2011-10-15 |fall   |  0|   10|       0|       6|          0|          1| 0.506667| 0.498725| 0.483333| 0.2580830|   1899|       3318|  5217| 20.773347| 5253.159|   -36.15895| 0.0090268| 1568.332| 0.0000025| -0.0232265|\n|     289|2011-10-16 |fall   |  0|   10|       0|       0|          0|          1| 0.511667| 0.503154| 0.486667| 0.2817170|   1748|       3293|  5041| 20.978347| 5284.498|  -243.49790| 0.0094459| 1568.225| 0.0001167| -0.1564425|\n|     290|2011-10-17 |fall   |  0|   10|       0|       1|          1|          1| 0.534167| 0.510725| 0.579583| 0.1753790|    713|       3857|  4570| 21.900847| 5425.523|  -855.52315| 0.0116325| 1566.985| 0.0017818| -0.5502641|\n|     291|2011-10-18 |fall   |  0|   10|       0|       2|          1|          2| 0.532500| 0.522721| 0.701667| 0.1100870|    637|       4111|  4748| 21.832500| 5415.075|  -667.07475| 0.0114537| 1567.514| 0.0010663| -0.4290171|\n|     292|2011-10-19 |fall   |  0|   10|       0|       3|          1|          3| 0.541739| 0.513848| 0.895217| 0.2433390|    254|       2170|  2424| 22.211299| 5472.983| -3048.98285| 0.0124791| 1551.090| 0.0243201| -1.9619161|\n|     293|2011-10-20 |fall   |  0|   10|       0|       4|          1|          1| 0.475833| 0.466525| 0.636250| 0.4222750|    471|       3724|  4195| 19.509153| 5059.898|  -864.89795| 0.0069790| 1566.962| 0.0010824| -0.5549889|\n|     294|2011-10-21 |fall   |  0|   10|       0|       5|          1|          1| 0.427500| 0.423596| 0.574167| 0.2213960|    676|       3628|  4304| 17.527500| 4756.957|  -452.95690| 0.0056282| 1567.959| 0.0002388| -0.2904565|\n|     295|2011-10-22 |fall   |  0|   10|       0|       6|          0|          1| 0.422500| 0.425492| 0.629167| 0.0926667|   1499|       2809|  4308| 17.322500| 4725.618|  -417.61795| 0.0056181| 1568.015| 0.0002026| -0.2677942|\n|     296|2011-10-23 |fall   |  0|   10|       0|       0|          0|          1| 0.421667| 0.422333| 0.741250| 0.0995125|   1619|       2762|  4381| 17.288347| 4720.397|  -339.39688| 0.0056187| 1568.123| 0.0001338| -0.2176356|\n|     297|2011-10-24 |fall   |  0|   10|       0|       1|          1|          1| 0.463333| 0.457067| 0.772083| 0.1187920|    699|       3488|  4187| 18.996653| 4981.551|  -794.55058| 0.0064121| 1567.177| 0.0008383| -0.5097028|\n|     298|2011-10-25 |fall   |  0|   10|       0|       2|          1|          1| 0.471667| 0.463375| 0.622917| 0.1666580|    695|       3992|  4687| 19.338347| 5033.786|  -346.78634| 0.0067732| 1568.114| 0.0001688| -0.2225033|\n|     299|2011-10-26 |fall   |  0|   10|       0|       3|          1|          2| 0.484167| 0.472846| 0.720417| 0.1486420|    404|       3490|  3894| 19.850847| 5112.134| -1218.13370| 0.0074414| 1565.609| 0.0022914| -0.7818357|\n|     300|2011-10-27 |fall   |  0|   10|       0|       4|          1|          2| 0.470000| 0.457046| 0.812917| 0.1977630|    240|       2419|  2659| 19.270000| 5023.338| -2364.33793| 0.0066956| 1558.048| 0.0077555| -1.5169350|\n|     301|2011-10-28 |fall   |  0|   10|       0|       5|          1|          2| 0.330833| 0.318812| 0.585833| 0.2294790|    456|       3291|  3747| 13.564153| 4151.069|  -404.06853| 0.0097369| 1568.034| 0.0003314| -0.2596440|\n|     302|2011-10-29 |fall   |  0|   10|       0|       6|          0|          3| 0.254167| 0.227913| 0.882500| 0.3513710|     57|        570|   627| 10.420847| 3670.542| -3043.54222| 0.0194520| 1551.029| 0.0383136| -1.9653663|\n|     303|2011-10-30 |fall   |  0|   10|       0|       0|          0|          1| 0.319167| 0.321329| 0.623750| 0.1766170|    885|       2446|  3331| 13.085847| 4077.949|  -746.94851| 0.0108468| 1567.307| 0.0012645| -0.4802391|\n|     304|2011-10-31 |fall   |  0|   10|       0|       1|          1|          1| 0.340000| 0.356063| 0.703333| 0.1063500|    362|       3307|  3669| 13.940000| 4208.525|  -539.52536| 0.0089575| 1567.799| 0.0005427| -0.3465487|\n|     305|2011-11-01 |fall   |  0|   11|       0|       2|          1|          1| 0.400833| 0.397088| 0.683750| 0.1355710|    410|       3658|  4068| 16.434153| 4589.814|  -521.81377| 0.0058547| 1567.835| 0.0003298| -0.3346488|\n|     306|2011-11-02 |fall   |  0|   11|       0|       3|          1|          1| 0.377500| 0.390133| 0.718750| 0.0820917|    370|       3816|  4186| 15.477500| 4443.567|  -257.56745| 0.0066197| 1568.213| 0.0000910| -0.1652463|\n|     307|2011-11-03 |fall   |  0|   11|       0|       4|          1|          1| 0.408333| 0.405921| 0.702083| 0.1368170|    318|       3656|  3974| 16.741653| 4636.822|  -662.82219| 0.0057212| 1567.529| 0.0005198| -0.4250515|\n|     308|2011-11-04 |fall   |  0|   11|       0|       5|          1|          2| 0.403333| 0.403392| 0.622500| 0.2717790|    470|       3576|  4046| 16.536653| 4605.483|  -559.48324| 0.0058041| 1567.761| 0.0003758| -0.3587977|\n|     309|2011-11-05 |fall   |  0|   11|       0|       6|          0|          1| 0.326667| 0.323854| 0.519167| 0.1890620|   1156|       2770|  3926| 13.393347| 4124.957|  -198.95693| 0.0101181| 1568.262| 0.0000836| -0.1278692|\n|     310|2011-11-06 |fall   |  0|   11|       0|       0|          0|          1| 0.348333| 0.362358| 0.734583| 0.0920542|    952|       2697|  3649| 14.281653| 4260.755|  -611.75484| 0.0083200| 1567.647| 0.0006473| -0.3928170|\n|     311|2011-11-07 |fall   |  0|   11|       0|       1|          1|          1| 0.395000| 0.400871| 0.758750| 0.0572250|    373|       3662|  4035| 16.195000| 4553.254|  -518.25375| 0.0059963| 1567.842| 0.0003332| -0.3323893|\n|     312|2011-11-08 |fall   |  0|   11|       0|       2|          1|          1| 0.408333| 0.412246| 0.721667| 0.0690375|    376|       3829|  4205| 16.741653| 4636.822|  -431.82219| 0.0057212| 1567.993| 0.0002206| -0.2769169|\n|     313|2011-11-09 |fall   |  0|   11|       0|       3|          1|          1| 0.400000| 0.409079| 0.758333| 0.0621958|    305|       3804|  4109| 16.400000| 4584.593|  -475.59270| 0.0058729| 1567.920| 0.0002748| -0.3050091|\n|     314|2011-11-10 |fall   |  0|   11|       0|       4|          1|          2| 0.380000| 0.373721| 0.813333| 0.1890670|    190|       2743|  2933| 15.580000| 4459.237| -1526.23692| 0.0065124| 1564.057| 0.0031422| -0.9791277|\n|     315|2011-11-11 |fall   |  0|   11|       1|       5|          0|          1| 0.324167| 0.306817| 0.446250| 0.3146750|    440|       2928|  3368| 13.290847| 4109.287|  -741.28745| 0.0103549| 1567.323| 0.0011878| -0.4764809|\n|     316|2011-11-12 |fall   |  0|   11|       0|       6|          0|          1| 0.356667| 0.357942| 0.552917| 0.2120620|   1275|       2792|  4067| 14.623347| 4312.991|  -245.99060| 0.0077498| 1568.223| 0.0000974| -0.1579089|\n|     317|2011-11-13 |fall   |  0|   11|       0|       0|          0|          1| 0.440833| 0.430550| 0.458333| 0.2817210|   1004|       2713|  3717| 18.074153| 4840.525| -1123.52533| 0.0057741| 1566.020| 0.0015075| -0.7205082|\n|     318|2011-11-14 |fall   |  0|   11|       0|       1|          1|          1| 0.530000| 0.524612| 0.587083| 0.3065960|    595|       3891|  4486| 21.730000| 5399.405|  -913.40527| 0.0111905| 1566.797| 0.0019522| -0.5873619|\n|     319|2011-11-15 |fall   |  0|   11|       0|       2|          1|          2| 0.530000| 0.507579| 0.688750| 0.1996330|    449|       3746|  4195| 21.730000| 5399.405| -1204.40527| 0.0111905| 1565.660| 0.0033942| -0.7744884|\n|     320|2011-11-16 |fall   |  0|   11|       0|       3|          1|          3| 0.456667| 0.451988| 0.930000| 0.1368290|    145|       1672|  1817| 18.723347| 4939.770| -3122.76950| 0.0061718| 1550.356| 0.0124576| -2.0030089|\n|     321|2011-11-17 |fall   |  0|   11|       0|       4|          1|          2| 0.341667| 0.323221| 0.575833| 0.3053620|    139|       2914|  3053| 14.008347| 4218.974| -1165.97376| 0.0088246| 1565.834| 0.0024965| -0.7488798|\n|     322|2011-11-18 |fall   |  0|   11|       0|       5|          1|          1| 0.274167| 0.272721| 0.410000| 0.1685330|    245|       3147|  3392| 11.240847| 3795.898|  -403.89800| 0.0163670| 1568.032| 0.0005642| -0.2604077|\n|     323|2011-11-19 |fall   |  0|   11|       0|       6|          0|          1| 0.329167| 0.324483| 0.502083| 0.2244960|    943|       2720|  3663| 13.495847| 4140.626|  -477.62640| 0.0098873| 1567.915| 0.0004704| -0.3069337|\n|     324|2011-11-20 |fall   |  0|   11|       0|       0|          0|          2| 0.463333| 0.457058| 0.684583| 0.1859500|    787|       2733|  3520| 18.996653| 4981.551| -1461.55058| 0.0064121| 1564.413| 0.0028365| -0.9375821|\n|     325|2011-11-21 |fall   |  0|   11|       0|       1|          1|          3| 0.447500| 0.445062| 0.910000| 0.1380540|    220|       2545|  2765| 18.347500| 4882.313| -2117.31268| 0.0059119| 1560.097| 0.0054829| -1.3579105|\n|     326|2011-11-22 |fall   |  0|   11|       0|       2|          1|          3| 0.416667| 0.421696| 0.962500| 0.1187920|     69|       1538|  1607| 17.083347| 4689.058| -3082.05794| 0.0056369| 1550.834| 0.0110713| -1.9763639|\n|     327|2011-11-23 |fall   |  0|   11|       0|       3|          1|          2| 0.440833| 0.430537| 0.757917| 0.3358250|    112|       2454|  2566| 18.074153| 4840.525| -2274.52533| 0.0057741| 1558.826| 0.0061782| -1.4586357|\n|     328|2011-11-24 |fall   |  0|   11|       1|       4|          0|          1| 0.373333| 0.372471| 0.549167| 0.1673040|    560|        935|  1495| 15.306653| 4417.450| -2922.44957| 0.0068120| 1552.590| 0.0120579| -1.8751236|\n|     329|2011-11-25 |fall   |  0|   11|       0|       5|          1|          1| 0.375000| 0.380671| 0.643750| 0.0988958|   1095|       1697|  2792| 15.375000| 4427.898| -1635.89797| 0.0067330| 1563.418| 0.0037339| -1.0495952|\n|     330|2011-11-26 |fall   |  0|   11|       0|       6|          0|          1| 0.375833| 0.385087| 0.681667| 0.0684208|   1249|       1819|  3068| 15.409153| 4433.119| -1365.11904| 0.0066946| 1564.913| 0.0025850| -0.8758460|\n|     331|2011-11-27 |fall   |  0|   11|       0|       0|          0|          1| 0.459167| 0.455800| 0.698333| 0.2089540|    810|       2261|  3071| 18.825847| 4955.439| -1884.43897| 0.0062568| 1561.811| 0.0045998| -1.2087698|\n|     332|2011-11-28 |fall   |  0|   11|       0|       1|          1|          1| 0.503478| 0.490122| 0.743043| 0.1421220|    253|       3614|  3867| 20.642598| 5233.171| -1366.17097| 0.0087722| 1564.900| 0.0034067| -0.8774390|\n|     333|2011-11-29 |fall   |  0|   11|       0|       2|          1|          2| 0.458333| 0.451375| 0.830833| 0.2580920|     96|       2818|  2914| 18.791653| 4950.212| -2036.21164| 0.0062278| 1560.715| 0.0053453| -1.3061050|\n|     334|2011-11-30 |fall   |  0|   11|       0|       3|          1|          1| 0.325000| 0.311221| 0.613333| 0.2711580|    188|       3425|  3613| 13.325000| 4114.509|  -501.50852| 0.0102753| 1567.872| 0.0005394| -0.3223441|\n|     335|2011-12-01 |fall   |  0|   12|       0|       4|          1|          1| 0.312500| 0.305554| 0.524583| 0.2201580|    182|       3545|  3727| 12.812500| 4036.161|  -309.16116| 0.0115405| 1568.158| 0.0002308| -0.1988402|\n|     336|2011-12-02 |fall   |  0|   12|       0|       5|          1|          1| 0.314167| 0.331433| 0.625833| 0.1007540|    268|       3672|  3940| 12.880847| 4046.610|  -106.60956| 0.0113630| 1568.314| 0.0000270| -0.0685609|\n|     337|2011-12-03 |fall   |  0|   12|       0|       6|          0|          1| 0.299167| 0.310604| 0.612917| 0.0957833|    706|       2908|  3614| 12.265847| 3952.593|  -338.59273| 0.0130573| 1568.123| 0.0003142| -0.2179366|\n|     338|2011-12-04 |fall   |  0|   12|       0|       0|          0|          1| 0.330833| 0.349100| 0.775833| 0.0839583|    634|       2851|  3485| 13.564153| 4151.069|  -666.06853| 0.0097369| 1567.518| 0.0009006| -0.4279985|\n|     339|2011-12-05 |fall   |  0|   12|       0|       1|          1|          2| 0.385833| 0.393925| 0.827083| 0.0622083|    233|       3578|  3811| 15.819153| 4495.797|  -684.79693| 0.0062858| 1567.475| 0.0006103| -0.4392681|\n|     340|2011-12-06 |fall   |  0|   12|       0|       2|          1|          3| 0.462500| 0.456400| 0.949583| 0.2325830|    126|       2468|  2594| 18.962500| 4976.330| -2382.32951| 0.0063797| 1557.894| 0.0074977| -1.5282352|\n|     341|2011-12-07 |fall   |  0|   12|       0|       3|          1|          3| 0.410000| 0.400246| 0.970417| 0.2661750|     50|        655|   705| 16.810000| 4647.271| -3942.27059| 0.0056989| 1539.596| 0.0183154| -2.5280524|\n|     342|2011-12-08 |fall   |  0|   12|       0|       4|          1|          1| 0.265833| 0.256938| 0.580000| 0.2400580|    150|       3172|  3322| 10.899153| 3743.662|  -421.66225| 0.0176053| 1568.005| 0.0006631| -0.2720322|\n|     343|2011-12-09 |fall   |  0|   12|       0|       5|          1|          1| 0.290833| 0.317542| 0.695833| 0.0827167|    261|       3359|  3620| 11.924153| 3900.357|  -280.35697| 0.0140931| 1568.189| 0.0002330| -0.1805477|\n|     344|2011-12-10 |fall   |  0|   12|       0|       6|          0|          1| 0.275000| 0.266412| 0.507500| 0.2332210|    502|       2688|  3190| 11.275000| 3801.119|  -611.11907| 0.0162469| 1567.643| 0.0012818| -0.3939865|\n|     345|2011-12-11 |fall   |  0|   12|       0|       0|          0|          1| 0.220833| 0.253154| 0.490000| 0.0665417|    377|       2366|  2743|  9.054153| 3461.612|  -718.61174| 0.0254577| 1567.369| 0.0028299| -0.4654709|\n|     346|2011-12-12 |fall   |  0|   12|       0|       1|          1|          1| 0.238333| 0.270196| 0.670833| 0.0634500|    143|       3167|  3310|  9.771653| 3571.298|  -261.29805| 0.0221701| 1568.207| 0.0003237| -0.1689675|\n|     347|2011-12-13 |fall   |  0|   12|       0|       2|          1|          1| 0.282500| 0.301138| 0.590000| 0.1405500|    155|       3368|  3523| 11.582500| 3848.127|  -325.12749| 0.0151963| 1568.139| 0.0003386| -0.2094968|\n|     348|2011-12-14 |fall   |  0|   12|       0|       3|          1|          2| 0.317500| 0.338362| 0.663750| 0.0609583|    178|       3562|  3740| 13.017500| 4067.500|  -327.50010| 0.0110162| 1568.137| 0.0002470| -0.2105792|\n|     349|2011-12-15 |fall   |  0|   12|       0|       4|          1|          2| 0.422500| 0.412237| 0.634167| 0.2680420|    181|       3528|  3709| 17.322500| 4725.618| -1016.61795| 0.0056181| 1566.440| 0.0012005| -0.6518982|\n|     350|2011-12-16 |fall   |  0|   12|       0|       5|          1|          2| 0.375000| 0.359825| 0.500417| 0.2605750|    178|       3399|  3577| 15.375000| 4427.898|  -850.89797| 0.0067330| 1567.006| 0.0010102| -0.5459377|\n|     351|2011-12-17 |fall   |  0|   12|       0|       6|          0|          2| 0.258333| 0.249371| 0.560833| 0.2431670|    275|       2464|  2739| 10.591653| 3696.654|  -957.65383| 0.0187774| 1566.631| 0.0036567| -0.6181920|\n|     352|2011-12-18 |fall   |  0|   12|       0|       0|          0|          1| 0.238333| 0.245579| 0.586250| 0.1697790|    220|       2211|  2431|  9.771653| 3571.298| -1140.29805| 0.0221701| 1565.910| 0.0061638| -0.7373698|\n|     353|2011-12-19 |fall   |  0|   12|       0|       1|          1|          1| 0.276667| 0.280933| 0.637500| 0.1728960|    260|       3143|  3403| 11.343347| 3811.567|  -408.56747| 0.0160087| 1568.025| 0.0005642| -0.2633703|\n|     354|2011-12-20 |fall   |  0|   12|       0|       2|          1|          2| 0.385833| 0.396454| 0.595417| 0.0615708|    216|       3534|  3750| 15.819153| 4495.797|  -745.79693| 0.0062858| 1567.314| 0.0007238| -0.4783970|\n|     632|2012-09-23 |fall   |  1|    9|       0|       0|          0|          1| 0.529167| 0.518933| 0.467083| 0.2232580|   2454|       5453|  7907| 21.695847| 5394.184|  2512.81579| 0.0111041| 1556.659| 0.0146579|  1.6157865|\n|     633|2012-09-24 |fall   |  1|    9|       0|       1|          1|          1| 0.514167| 0.502513| 0.492917| 0.1424040|   1001|       6435|  7436| 21.080847| 5300.167|  2135.83263| 0.0096646| 1559.920| 0.0091901|  1.3723809|\n|     634|2012-09-25 |fall   |  1|    9|       0|       2|          1|          1| 0.550000| 0.544179| 0.570000| 0.2363210|    845|       6693|  7538| 22.550000| 5524.761|  2013.23894| 0.0134661| 1560.832| 0.0114651|  1.2960983|\n|     635|2012-09-26 |fall   |  1|    9|       0|       3|          1|          1| 0.635000| 0.596613| 0.630833| 0.2444000|    787|       6946|  7733| 26.035000| 6057.523|  1675.47688| 0.0274742| 1563.067| 0.0166712|  1.0863918|\n|     636|2012-09-27 |fall   |  1|    9|       0|       4|          1|          2| 0.650000| 0.607975| 0.690833| 0.1343420|    751|       6642|  7393| 26.650000| 6151.540|  1241.46004| 0.0306750| 1565.435| 0.0102868|  0.8063000|\n|     637|2012-09-28 |fall   |  1|    9|       0|       5|          1|          2| 0.619167| 0.585863| 0.690000| 0.1641790|   1045|       6370|  7415| 25.385847| 5958.285|  1456.71478| 0.0243328| 1564.367| 0.0110893|  0.9430230|\n|     638|2012-09-29 |fall   |  1|    9|       0|       6|          0|          1| 0.542500| 0.530296| 0.542917| 0.2276040|   2589|       5966|  8555| 22.242500| 5477.753|  3077.24736| 0.0125672| 1550.765| 0.0249526|  1.9801917|\n|     639|2012-09-30 |fall   |  1|    9|       0|       0|          0|          1| 0.526667| 0.517663| 0.583333| 0.1349580|   2015|       4874|  6889| 21.593347| 5378.515|  1510.48527| 0.0108490| 1564.127| 0.0051721|  0.9711444|\n|     640|2012-10-01 |fall   |  1|   10|       0|       1|          1|          2| 0.520833| 0.512000| 0.649167| 0.0908042|    763|       6015|  6778| 21.354153| 5341.948|  1436.05155| 0.0102773| 1564.534| 0.0044234|  0.9230216|\n|     641|2012-10-02 |fall   |  1|   10|       0|       2|          1|          3| 0.590833| 0.542333| 0.871667| 0.1044750|    315|       4324|  4639| 24.224153| 5780.694| -1141.69369| 0.0193192| 1565.911| 0.0053530| -0.7371984|\n|     642|2012-10-03 |fall   |  1|   10|       0|       3|          1|          2| 0.657500| 0.599133| 0.793750| 0.0665458|    728|       6844|  7572| 26.957500| 6198.548|  1373.45162| 0.0323574| 1564.779| 0.0133272|  0.8928006|\n|     643|2012-10-04 |fall   |  1|   10|       0|       4|          1|          2| 0.657500| 0.607975| 0.722917| 0.1175460|    891|       6437|  7328| 26.957500| 6198.548|  1129.45162| 0.0323574| 1565.931| 0.0090125|  0.7341905|\n|     644|2012-10-05 |fall   |  1|   10|       0|       5|          1|          1| 0.615000| 0.580187| 0.627500| 0.1063500|   1516|       6640|  8156| 25.215000| 5932.167|  2223.83266| 0.0235465| 1559.081| 0.0249687|  1.4390469|\n|     645|2012-10-06 |fall   |  1|   10|       0|       6|          0|          1| 0.554167| 0.538521| 0.664167| 0.2680250|   3031|       4934|  7965| 22.720847| 5550.879|  2414.12107| 0.0139892| 1557.529| 0.0171441|  1.5545934|\n|     646|2012-10-07 |fall   |  1|   10|       0|       0|          0|          2| 0.415833| 0.419813| 0.708333| 0.1411620|    781|       2729|  3510| 17.049153| 4683.831| -1173.83060| 0.0056423| 1565.808| 0.0016075| -0.7527187|\n|     647|2012-10-08 |fall   |  1|   10|       1|       1|          0|          2| 0.383333| 0.387608| 0.709583| 0.1896790|    874|       4604|  5478| 15.716653| 4480.127|   997.87254| 0.0063789| 1566.508| 0.0013153|  0.6401228|\n|     648|2012-10-09 |fall   |  1|   10|       0|       2|          1|          2| 0.446667| 0.438112| 0.761667| 0.1903000|    601|       5791|  6392| 18.313347| 4877.092|  1514.90839| 0.0058923| 1564.123| 0.0027974|  0.9715569|\n|     649|2012-10-10 |fall   |  1|   10|       0|       3|          1|          1| 0.514167| 0.503142| 0.630833| 0.1878210|    780|       6911|  7691| 21.080847| 5300.167|  2390.83263| 0.0096646| 1557.784| 0.0115155|  1.5362313|\n|     650|2012-10-11 |fall   |  1|   10|       0|       4|          1|          1| 0.435000| 0.431167| 0.463333| 0.1815960|    834|       6736|  7570| 17.835000| 4803.965|  2766.03468| 0.0056890| 1554.253| 0.0090007|  1.7737611|\n|     651|2012-10-12 |fall   |  1|   10|       0|       5|          1|          1| 0.437500| 0.433071| 0.539167| 0.2350920|   1060|       6222|  7282| 17.937500| 4819.635|  2462.36521| 0.0057215| 1557.186| 0.0071740|  1.5790542|\n|     652|2012-10-13 |fall   |  1|   10|       0|       6|          0|          1| 0.393333| 0.391396| 0.494583| 0.1461420|   2252|       4857|  7109| 16.126653| 4542.805|  2566.19465| 0.0060429| 1556.218| 0.0082349|  1.6459035|\n|     653|2012-10-14 |fall   |  1|   10|       0|       0|          0|          1| 0.521667| 0.508204| 0.640417| 0.2786120|   2080|       4559|  6639| 21.388347| 5347.176|  1291.82421| 0.0103570| 1565.260| 0.0036079|  0.8303530|\n|     654|2012-10-15 |fall   |  1|   10|       0|       1|          1|          2| 0.561667| 0.539150| 0.707500| 0.2960370|    760|       5115|  5875| 23.028347| 5597.887|   277.11265| 0.0149732| 1568.192| 0.0002423|  0.1785381|\n|     655|2012-10-16 |fall   |  1|   10|       0|       2|          1|          1| 0.468333| 0.460846| 0.558333| 0.1822210|    922|       6612|  7534| 19.201653| 5012.890|  2521.11047| 0.0066206| 1556.635| 0.0087180|  1.6174576|\n|     656|2012-10-17 |fall   |  1|   10|       0|       3|          1|          1| 0.455833| 0.450108| 0.692917| 0.1013710|    979|       6482|  7461| 18.689153| 4934.542|  2526.45784| 0.0061447| 1556.590| 0.0081180|  1.6205002|\n|     657|2012-10-18 |fall   |  1|   10|       0|       4|          1|          2| 0.522500| 0.512625| 0.728333| 0.2369370|   1008|       6501|  7509| 21.422500| 5352.397|  2156.60314| 0.0104373| 1559.749| 0.0101346|  1.3862679|\n|     658|2012-10-19 |fall   |  1|   10|       0|       5|          1|          2| 0.563333| 0.537896| 0.815000| 0.1349540|    753|       4671|  5424| 23.096653| 5608.329|  -184.32949| 0.0151992| 1568.272| 0.0001089| -0.1187734|\n|     659|2012-10-20 |fall   |  1|   10|       0|       6|          0|          1| 0.484167| 0.472842| 0.572917| 0.1175370|   2806|       5284|  8090| 19.850847| 5112.134|  2977.86630| 0.0074414| 1551.973| 0.0136937|  1.9112862|\n|     660|2012-10-21 |fall   |  1|   10|       0|       0|          0|          1| 0.464167| 0.456429| 0.510000| 0.1660540|   2132|       4692|  6824| 19.030847| 4986.778|  1837.22208| 0.0064452| 1562.133| 0.0045055|  1.1785943|\n|     661|2012-10-22 |fall   |  1|   10|       0|       1|          1|          1| 0.487500| 0.482942| 0.568333| 0.0814833|    830|       6228|  7058| 19.987500| 5133.024|  1924.97576| 0.0076452| 1561.517| 0.0058813|  1.2356355|\n|     662|2012-10-23 |fall   |  1|   10|       0|       2|          1|          1| 0.544167| 0.530304| 0.641667| 0.0945458|    841|       6625|  7466| 22.310847| 5488.201|  1977.79896| 0.0127623| 1561.100| 0.0104717|  1.2728285|\n|     663|2012-10-24 |fall   |  1|   10|       0|       3|          1|          1| 0.587500| 0.558721| 0.636250| 0.0727792|    795|       6898|  7693| 24.087500| 5759.803|  1933.19686| 0.0187807| 1561.380| 0.0149039|  1.2479341|\n|     664|2012-10-25 |fall   |  1|   10|       0|       4|          1|          2| 0.550000| 0.529688| 0.800417| 0.1243750|    875|       6484|  7359| 22.550000| 5524.761|  1834.23894| 0.0134661| 1562.109| 0.0095170|  1.1808603|\n|     665|2012-10-26 |fall   |  1|   10|       0|       5|          1|          2| 0.545833| 0.522750| 0.807083| 0.1324670|   1182|       6262|  7444| 22.379153| 5498.643|  1945.35682| 0.0129599| 1561.334| 0.0102920|  1.2520754|\n|     666|2012-10-27 |fall   |  1|   10|       0|       6|          0|          2| 0.530000| 0.515133| 0.720000| 0.2356920|   2643|       5209|  7852| 21.730000| 5399.405|  2452.59473| 0.0111905| 1557.213| 0.0140748|  1.5771321|\n|     667|2012-10-28 |fall   |  1|   10|       0|       0|          0|          2| 0.477500| 0.467771| 0.694583| 0.3980080|    998|       3461|  4459| 19.577500| 5070.346|  -611.34635| 0.0070661| 1567.649| 0.0005476| -0.3923067|\n|     668|2012-10-29 |fall   |  1|   10|       0|       1|          1|          3| 0.440000| 0.439400| 0.880000| 0.3582000|      2|         20|    22| 18.040000| 4835.304| -4813.30426| 0.0057599| 1525.293| 0.0275988| -3.0867133|\n|     669|2012-10-30 |fall   |  1|   10|       0|       2|          1|          2| 0.318182| 0.309909| 0.825455| 0.2130090|     87|       1009|  1096| 13.045462| 4071.775| -2975.77474| 0.0109466| 1551.938| 0.0202584| -1.9133251|\n|     670|2012-10-31 |fall   |  1|   10|       0|       3|          1|          2| 0.357500| 0.361100| 0.666667| 0.1666670|    419|       5147|  5566| 14.657500| 4318.212|  1247.78834| 0.0076965| 1565.473| 0.0024880|  0.8009719|\n|     671|2012-11-01 |fall   |  1|   11|       0|       4|          1|          2| 0.365833| 0.369942| 0.581667| 0.1573460|    466|       5520|  5986| 14.999153| 4370.441|  1615.55885| 0.0072006| 1563.538| 0.0038982|  1.0367896|\n|     672|2012-11-02 |fall   |  1|   11|       0|       5|          1|          1| 0.355000| 0.356042| 0.522083| 0.2661750|    618|       5229|  5847| 14.555000| 4302.542|  1544.45781| 0.0078584| 1563.948| 0.0038932|  0.9914888|\n|     673|2012-11-03 |fall   |  1|   11|       0|       6|          0|          2| 0.343333| 0.323846| 0.491250| 0.2705290|   1029|       4109|  5138| 14.076653| 4229.416|   908.58410| 0.0086944| 1566.817| 0.0014932|  0.5835257|\n|     674|2012-11-04 |fall   |  1|   11|       0|       0|          0|          1| 0.325833| 0.329538| 0.532917| 0.1791080|   1201|       3906|  5107| 13.359153| 4119.730|   987.27041| 0.0101964| 1566.540| 0.0020739|  0.6345418|\n|     675|2012-11-05 |fall   |  1|   11|       0|       1|          1|          1| 0.319167| 0.308075| 0.494167| 0.2363250|    378|       4881|  5259| 13.085847| 4077.949|  1181.05149| 0.0108468| 1565.763| 0.0031614|  0.7593389|\n|     676|2012-11-06 |fall   |  1|   11|       0|       2|          1|          1| 0.280833| 0.281567| 0.567083| 0.1735130|    466|       5220|  5686| 11.514153| 3837.679|  1848.32092| 0.0154251| 1562.001| 0.0111135|  1.1911093|\n|     677|2012-11-07 |fall   |  1|   11|       0|       3|          1|          2| 0.295833| 0.274621| 0.547500| 0.3041080|    326|       4709|  5035| 12.129153| 3931.696|  1103.30408| 0.0134636| 1566.085| 0.0034426|  0.7102926|\n|     678|2012-11-08 |fall   |  1|   11|       0|       4|          1|          1| 0.352174| 0.341891| 0.333478| 0.3478350|    340|       4975|  5315| 14.439134| 4284.829|  1030.17058| 0.0080488| 1566.384| 0.0017747|  0.6613976|\n|     679|2012-11-09 |fall   |  1|   11|       0|       5|          1|          1| 0.361667| 0.355413| 0.540833| 0.2145580|    709|       5283|  5992| 14.828347| 4344.330|  1647.67046| 0.0074401| 1563.344| 0.0041915|  1.0575249|\n|     680|2012-11-10 |fall   |  1|   11|       0|       6|          0|          1| 0.389167| 0.393937| 0.645417| 0.0578458|   2090|       4446|  6536| 15.955847| 4516.694|  2019.30626| 0.0061711| 1560.842| 0.0052084|  1.2952243|\n|     681|2012-11-11 |fall   |  1|   11|       0|       0|          0|          1| 0.420833| 0.421713| 0.659167| 0.1275000|   2290|       4562|  6852| 17.254153| 4715.170|  2136.83045| 0.0056201| 1559.947| 0.0053057|  1.3702269|\n|     682|2012-11-12 |fall   |  1|   11|       1|       1|          0|          1| 0.485000| 0.475383| 0.741667| 0.1735170|   1097|       5172|  6269| 19.885000| 5117.355|  1151.64523| 0.0074913| 1565.898| 0.0020620|  0.7391799|\n|     683|2012-11-13 |fall   |  1|   11|       0|       2|          1|          2| 0.343333| 0.323225| 0.662917| 0.3420460|    327|       3767|  4094| 14.076653| 4229.416|  -135.41590| 0.0086944| 1568.301| 0.0000332| -0.0869690|\n|     684|2012-11-14 |fall   |  1|   11|       0|       3|          1|          1| 0.289167| 0.281563| 0.552083| 0.1996250|    373|       5122|  5495| 11.855847| 3889.915|  1605.08516| 0.0143083| 1563.566| 0.0077565|  1.0337753|\n|     685|2012-11-15 |fall   |  1|   11|       0|       4|          1|          2| 0.321667| 0.324492| 0.620417| 0.1529870|    320|       5125|  5445| 13.188347| 4093.618|  1351.38202| 0.0105978| 1564.968| 0.0040420|  0.8687410|\n|     686|2012-11-16 |fall   |  1|   11|       0|       5|          1|          1| 0.345000| 0.347204| 0.524583| 0.1710250|    484|       5214|  5698| 14.145000| 4239.864|  1458.13570| 0.0085669| 1564.423| 0.0037884|  0.9364074|\n|     687|2012-11-17 |fall   |  1|   11|       0|       6|          0|          1| 0.325000| 0.326383| 0.545417| 0.1797290|   1313|       4316|  5629| 13.325000| 4114.509|  1514.49148| 0.0102753| 1564.107| 0.0049189|  0.9734379|\n|     688|2012-11-18 |fall   |  1|   11|       0|       0|          0|          1| 0.342500| 0.337746| 0.692917| 0.2276120|    922|       3747|  4669| 14.042500| 4224.195|   444.80517| 0.0087592| 1567.971| 0.0003606|  0.2856793|\n|     689|2012-11-19 |fall   |  1|   11|       0|       1|          1|          2| 0.380833| 0.375621| 0.623333| 0.2350670|    449|       5050|  5499| 15.614153| 4464.458|  1034.54201| 0.0064780| 1566.371| 0.0014360|  0.6636789|\n|     690|2012-11-20 |fall   |  1|   11|       0|       2|          1|          2| 0.374167| 0.380667| 0.685000| 0.0827250|    534|       5100|  5634| 15.340847| 4422.677|  1211.32310| 0.0067722| 1565.641| 0.0020593|  0.7772024|\n|     691|2012-11-21 |fall   |  1|   11|       0|       3|          1|          1| 0.353333| 0.364892| 0.613750| 0.1032460|    615|       4531|  5146| 14.486653| 4292.094|   853.90621| 0.0079698| 1566.995| 0.0012072|  0.5482092|\n|     692|2012-11-22 |fall   |  1|   11|       1|       4|          0|          1| 0.340000| 0.350371| 0.580417| 0.0528708|    955|       1470|  2425| 13.940000| 4208.525| -1783.52536| 0.0089575| 1562.476| 0.0059310| -1.1455967|\n|     693|2012-11-23 |fall   |  1|   11|       0|       5|          1|          1| 0.368333| 0.378779| 0.568750| 0.1480210|   1603|       2307|  3910| 15.101653| 4386.111|  -476.11062| 0.0070650| 1567.919| 0.0003321| -0.3055245|\n|     694|2012-11-24 |fall   |  1|   11|       0|       6|          0|          1| 0.278333| 0.248742| 0.404583| 0.3768710|    532|       1745|  2277| 11.411653| 3822.010| -1545.00961| 0.0157733| 1563.910| 0.0079462| -0.9958231|\n|     695|2012-11-25 |fall   |  1|   11|       0|       0|          0|          1| 0.245833| 0.257583| 0.468333| 0.1505000|    309|       2115|  2424| 10.079153| 3618.306| -1194.30647| 0.0208523| 1565.678| 0.0063424| -0.7717743|\n|     696|2012-11-26 |fall   |  1|   11|       0|       1|          1|          1| 0.313333| 0.339004| 0.535417| 0.0466500|    337|       4750|  5087| 12.846653| 4041.382|  1045.61777| 0.0114514| 1566.318| 0.0026192|  0.6724694|\n|     697|2012-11-27 |fall   |  1|   11|       0|       2|          1|          2| 0.291667| 0.281558| 0.786667| 0.2375620|    123|       3836|  3959| 11.958347| 3905.584|    53.41569| 0.0139864| 1568.329| 0.0000084|  0.0343974|\n|     698|2012-11-28 |fall   |  1|   11|       0|       3|          1|          1| 0.296667| 0.289762| 0.506250| 0.2108210|    198|       5062|  5260| 12.163347| 3936.923|  1323.07675| 0.0133609| 1565.099| 0.0049120|  0.8517350|\n|     699|2012-11-29 |fall   |  1|   11|       0|       4|          1|          1| 0.280870| 0.298422| 0.555652| 0.1155220|    243|       5080|  5323| 11.515670| 3837.911|  1485.08901| 0.0154200| 1564.248| 0.0071722|  0.9570301|\n|     700|2012-11-30 |fall   |  1|   11|       0|       5|          1|          1| 0.298333| 0.323867| 0.649583| 0.0584708|    362|       5306|  5668| 12.231653| 3947.365|  1720.63461| 0.0131579| 1562.860| 0.0081778|  1.1075502|\n|     701|2012-12-01 |fall   |  1|   12|       0|       6|          0|          2| 0.298333| 0.316904| 0.806667| 0.0597042|    951|       4240|  5191| 12.231653| 3947.365|  1243.63461| 0.0131579| 1565.477| 0.0042721|  0.8005115|\n|     702|2012-12-02 |fall   |  1|   12|       0|       0|          0|          2| 0.347500| 0.359208| 0.823333| 0.1243790|    892|       3757|  4649| 14.247500| 4255.534|   393.46623| 0.0083807| 1568.050| 0.0002698|  0.2526583|\n|     703|2012-12-03 |fall   |  1|   12|       0|       1|          1|          1| 0.452500| 0.455796| 0.767500| 0.0827208|    555|       5679|  6234| 18.552500| 4913.652|  1320.34838| 0.0060435| 1565.136| 0.0021802|  0.8468441|\n|     704|2012-12-04 |fall   |  1|   12|       0|       2|          1|          1| 0.475833| 0.469054| 0.733750| 0.1741290|    551|       6055|  6606| 19.509153| 5059.898|  1546.10205| 0.0069790| 1563.943| 0.0034588|  0.9921048|\n|     705|2012-12-05 |fall   |  1|   12|       0|       3|          1|          1| 0.438333| 0.428012| 0.485000| 0.3240210|    331|       5398|  5729| 17.971653| 4824.856|   904.14414| 0.0057336| 1566.836| 0.0009693|  0.5798089|\n|     706|2012-12-06 |fall   |  1|   12|       0|       4|          1|          1| 0.255833| 0.258204| 0.508750| 0.1747540|    340|       5035|  5375| 10.489153| 3680.984|  1694.01564| 0.0191802| 1562.995| 0.0116971|  1.0937584|\n|     707|2012-12-07 |fall   |  1|   12|       0|       5|          1|          2| 0.320833| 0.321958| 0.764167| 0.1306000|    349|       4659|  5008| 13.154153| 4088.391|   919.60936| 0.0106802| 1566.776| 0.0018866|  0.5911989|\n|     708|2012-12-08 |fall   |  1|   12|       0|       6|          0|          2| 0.381667| 0.389508| 0.911250| 0.1013790|   1153|       4429|  5582| 15.648347| 4469.685|  1112.31468| 0.0064443| 1566.064| 0.0016512|  0.7135594|\n|     709|2012-12-09 |fall   |  1|   12|       0|       0|          0|          2| 0.384167| 0.390146| 0.905417| 0.1579750|    441|       2787|  3228| 15.750847| 4485.355| -1257.35480| 0.0063471| 1565.433| 0.0020777| -0.8065645|\n|     710|2012-12-10 |fall   |  1|   12|       0|       1|          1|          2| 0.435833| 0.435575| 0.925000| 0.1903080|    329|       4841|  5170| 17.869153| 4809.186|   360.81362| 0.0056992| 1568.096| 0.0001534|  0.2313783|\n|     711|2012-12-11 |fall   |  1|   12|       0|       2|          1|          2| 0.353333| 0.338363| 0.596667| 0.2960370|    282|       5219|  5501| 14.486653| 4292.094|  1208.90621| 0.0079698| 1565.648| 0.0024196|  0.7761198|\n|     712|2012-12-12 |fall   |  1|   12|       0|       3|          1|          2| 0.297500| 0.297338| 0.538333| 0.1629370|    310|       5009|  5319| 12.197500| 3942.144|  1376.85568| 0.0132591| 1564.831| 0.0052778|  0.8863096|\n|     713|2012-12-13 |fall   |  1|   12|       0|       4|          1|          1| 0.295833| 0.294188| 0.485833| 0.1741290|    425|       5107|  5532| 12.129153| 3931.696|  1600.30408| 0.0134636| 1563.598| 0.0072428|  1.0302546|\n|     714|2012-12-14 |fall   |  1|   12|       0|       5|          1|          1| 0.281667| 0.294192| 0.642917| 0.1312290|    429|       5182|  5611| 11.548347| 3842.906|  1768.09358| 0.0153103| 1562.540| 0.0100917|  1.1393421|\n|     715|2012-12-15 |fall   |  1|   12|       0|       6|          0|          1| 0.324167| 0.338383| 0.650417| 0.1063500|    767|       4280|  5047| 13.290847| 4109.287|   937.71255| 0.0103549| 1566.715| 0.0019006|  0.6027380|\n|     716|2012-12-16 |fall   |  1|   12|       0|       0|          0|          2| 0.362500| 0.369938| 0.838750| 0.1007420|    538|       3248|  3786| 14.862500| 4349.551|  -563.55061| 0.0073909| 1567.752| 0.0004870| -0.3616949|\n|     717|2012-12-17 |fall   |  1|   12|       0|       1|          1|          2| 0.393333| 0.401500| 0.907083| 0.0982583|    212|       4373|  4585| 16.126653| 4542.805|    42.19465| 0.0060429| 1568.331| 0.0000022|  0.0270628|\n|     718|2012-12-18 |fall   |  1|   12|       0|       2|          1|          1| 0.410833| 0.409708| 0.666250| 0.2214040|    433|       5124|  5557| 16.844153| 4652.492|   904.50834| 0.0056888| 1566.835| 0.0009624|  0.5800294|\n|     719|2012-12-19 |fall   |  1|   12|       0|       3|          1|          1| 0.332500| 0.342162| 0.625417| 0.1840920|    333|       4934|  5267| 13.632500| 4161.517|  1105.48306| 0.0095891| 1566.085| 0.0024424|  0.7103019|\n|     720|2012-12-20 |fall   |  1|   12|       0|       4|          1|          2| 0.330000| 0.335217| 0.667917| 0.1324630|    314|       3814|  4128| 13.530000| 4145.847|   -17.84747| 0.0098118| 1568.334| 0.0000007| -0.0114688|\n\n\n:::\n:::\n\n\n## ANOVA in R\n\n- `supernova` from the `supernova` package takes a linear model a decomposes the variation into it's $SSM$ and $SSE$ (look at the `sumsq` column)... which do we think is which? \n- How can we get $SST$?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall_fit |>\n  supernova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: count ~ temp_orig\n\n                                    SS  df           MS      F   PRE     p\n ----- --------------- | ------------- --- ------------ ------ ----- -----\n Model (error reduced) |  80855681.350   1 80855681.350 33.060 .1581 .0000\n Error (from model)    | 430442808.925 176  2445697.778                   \n ----- --------------- | ------------- --- ------------ ------ ----- -----\n Total (empty model)   | 511298490.275 177  2888692.035                   \n```\n\n\n:::\n:::\n\n\n## Another Example {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nseason_model <- lm(count ~ season, data = bikeshare)\n\nseason_model |>  supernova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: count ~ season\n\n                                     SS  df            MS       F   PRE     p\n ----- --------------- | -------------- --- ------------- ------- ----- -----\n Model (error reduced) |  950595868.458   3 316865289.486 128.770 .3470 .0000\n Error (from model)    | 1788939523.588 727   2460714.613                    \n ----- --------------- | -------------- --- ------------- ------- ----- -----\n Total (empty model)   | 2739535392.047 730   3752788.208                    \n```\n\n\n:::\n:::\n\n\n## Evaluating and Comparing Models\n\n## $R^2$: Percent Reduction in Error (PRE)\n\n- Our goal is to maximize the variation explained by our model (minimize the leftover error for our model)\n- It makes sense to ask... \"How much has our model reduced the Total Error By\":\n$$\nPRE = R^2 = \\frac{SSM}{SST}\n$$\n- We call this quantity the **Precent Reduction in Error (PRE)**... \n- More commonly it is simply referred to as $R^2$\n\n## Back to our examples {.smaller}\n\n::::{.columns}\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntemp_fit <- lm(count ~ temp_orig, data = bikeshare)\ntemp_fit |> supernova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: count ~ temp_orig\n\n                                     SS  df             MS       F   PRE     p\n ----- --------------- | -------------- --- -------------- ------- ----- -----\n Model (error reduced) | 1078688585.170   1 1078688585.170 473.472 .3937 .0000\n Error (from model)    | 1660846806.877 729    2278253.507                    \n ----- --------------- | -------------- --- -------------- ------- ----- -----\n Total (empty model)   | 2739535392.047 730    3752788.208                    \n```\n\n\n:::\n:::\n\n:::\n:::{.column}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nseason_model <- lm(count ~ season, data = bikeshare)\n\nseason_model |>  supernova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: count ~ season\n\n                                     SS  df            MS       F   PRE     p\n ----- --------------- | -------------- --- ------------- ------- ----- -----\n Model (error reduced) |  950595868.458   3 316865289.486 128.770 .3470 .0000\n Error (from model)    | 1788939523.588 727   2460714.613                    \n ----- --------------- | -------------- --- ------------- ------- ----- -----\n Total (empty model)   | 2739535392.047 730   3752788.208                    \n```\n\n\n:::\n:::\n\n:::\n::::\n\n::: question\n1. Which model has a better $R^2$?\n2. Why do you think I didn't just use `fall_fit` for the first model?\n:::\n\n## Recall: Correlation Coefficient\n\n-   The **correlation coefficient**, $r$, is a number between -1 and +1 that measures how strong the linear relationship between two variables $x$ and $y$ is.\n\n$$\nr = \\frac{\\sum(x_i - \\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum(x_i-\\bar{x})^2\\sum(y_i-\\bar{y})^2}}\n= \\frac{\\sum(x_i - \\bar{x})(y_i-\\bar{y})}{s_xs_y}\n$$\n\n## Interesting Property of $R^2$ {.smaller}\n\n-   **R-squared** AKA $R^2$ AKA **PRE** AKA the **Coefficient of Determination** is not just the proportion of variability in the outcome explained by the regression model it is also the correlation between our *fitted* and *actual values* squared...\n$$\nR^2 = Cor(y, \\hat{y})^2\n$$\n\n::: question\n1. What should be the minimum and maximum value of $R^2$ based on this information?\n2. Do we want $R^2$ to be big or small?\n:::\n\n## $R^2$\n\n::: incremental\n-   Ranges between 0 (terrible predictor) and 1 (perfect predictor)\n-   Has no units\n-   Calculate with `rsq()` from `yardstick` package from earlier using the augmented data or `supernova`:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfall_aug <- augment(fall_fit)\n\nrsq(fall_aug, truth = count, estimate = .fitted) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|.metric |.estimator | .estimate|\n|:-------|:----------|---------:|\n|rsq     |standard   | 0.1581379|\n\n\n:::\n:::\n\n:::\n\n## Interpreting $R^2$ {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: poll\n🗳️ **Discussion**\n\n::: midi\nThe $R^2$ of the model for `count` from `temp_orig` is 15.8%. Which of the following is the correct interpretation of this value?\n:::\n\n1.  `temp_orig` correctly predicts 15.8% of `count`.\n2.  15.8% of the variability in `count` can be explained by `temp_orig`.\n3.  15.8% of the variability in `temp_orig` can be explained by `count`.\n4.  15.8% of the time `count` can be predicted by `temp_orig`.\n:::\n\n## RMSE {.smaller}\n\n::: incremental\n-   **Root mean square error, RMSE**: A measure of the average error (average difference between observed and predicted values of the outcome)\n$$\nRMSE = \\sqrt{\\frac{\\sum_{i = 1}^n (y_i - \\hat{y}_i)^2}{n}}\n$$\n    + Sometimes people just care about numerator (SSE) or version without the square-root (MSE)\n    + Sometimes the denominator may something other than $n$ like $n-1$ or $n-k$ instead\n-   Interpretation (kind of): how much does my model miss by, on average.\n:::\n\n::: question\n1. What should be the minimum and maximum of RMSE? [0 and infinity]{.fragment}\n2. What units are RMSE in? [the same units as the response variable]{.fragment}\n:::\n\n## RMSE in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrmse(fall_aug, truth = count, estimate = .fitted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       1555.\n```\n\n\n:::\n:::\n\n\n# Back to your coffee truck models\n\n## Your three models {.smaller}\n\nRecall from the start of class, you fit three models to your own coffee truck data.\n\n::: question\nNow that you've seen residuals, SSE, $R^2$, and RMSE — which of your three models do you expect to win? Has your prediction from earlier changed?\n:::\n\n## Work time\n\n::: appex\n📋 [AE 06 - Comparing Models with the Coffee Truck](../ae/ae-06-coffee-truck-eval.qmd)\n:::\n\nComplete Exercises 2-4. If time permits, complete Exercise 5.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_10d7f31b\" minutes=\"15\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## Quantitative vs. categorical price {.smaller}\n\n::: incremental\n- `fit_cat`:  (`Price` as the explanatory variable) fits a separate mean for each of the 4 price levels — it has more \"freedom\" to match the data.\n- `fit_num` (`PriceNum` as the explanatory variable) forces those 4 means onto a single straight line.\n- Because a line is a *special case* of \"4 free means,\" `fit_cat`'s $R^2$ can never be smaller than `fit_num`'s $R^2$.\n- So why not always use the categorical version?\n    - It can't predict at a price it hasn't seen, like \\$3.50.\n    - It has no single \"per dollar\" slope to interpret or report.\n    - It uses more parameters to explain (possibly) only a little more variation\n:::\n\n## Using the word \"Good\"\n\n-   There is no such thing as a \"Good\" $R^2$ or, especially, RMSE without **context**.\n-   Whether your model is a \"Good\" model depends on many things:\n    +   What are you using your model for?\n    +   How good are other models?\n    +   **What else was varying in the data you fit it to?**\n\n## Recap {.smaller}\n\n-   A **residual** is the leftover gap between an observed value and the model's prediction: $e_i = y_i - \\hat{y}_i$.\n-   The **least squares method** picks $\\hat{\\beta}_0, \\hat{\\beta}_1$ to minimize $\\sum e_i^2$.\n-   Can decompose total variation (SST) into variation explained by the model (SSM) and leftover variation (SSE).\n-   Two metrics for evaluating and comparing models:\n    +   $R^2$: What proportion of the variation in the response variable is explained by the model?\n    +   $RMSE$: How far does my model miss by, on average?\n-   $R^2$ depends on the data it was fit to, not just the true relationship — so it can't be compared across data sets that vary different things.\n",
    "supporting": [
      "06-slr-fitting-eval_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}